package com.portafolio.motors.ing.sis.proyecto.vista;

import com.portafolio.motors.ing.sis.proyecto.controlador.concesionarioBuilder;
import com.portafolio.motors.ing.sis.proyecto.modelo.SQLstatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Yonier Asprilla
 */
public class addFeatures extends javax.swing.JPanel {

    private main main;
    private concesionarioBuilder cb;
    SQLstatement instance;

    public addFeatures(main main) {
        this.main = main;
        this.instance = new SQLstatement();
        initComponents();
        btnNew.setEnabled(false);
    }

    private void add() {
        try {
            int id = Integer.parseInt(txtId.getText());
            String desc = txtDescripcion.getText();
            String maxVel = txtVelMax.getText();
            String maxTorque = txtMaxTorque.getText();
            String combustible = txtCombustible.getText();
            String aceleracion = txtAceleracion.getText();
            String kilometraje = txtKilometraje.getText();
            String suspension = txtSuspension.getText();
            String radiador = txtRadiador.getText();

            if (txtId.equals("") && txtDescripcion.equals("") && txtVelMax.equals("") && txtMaxTorque.equals("") && txtCombustible.equals("")
                    && txtAceleracion.equals("") && txtKilometraje.equals("") && txtSuspension.equals("") && txtRadiador.equals("")) {
                JOptionPane.showMessageDialog(null, "¡Aun tienes campos por llenar!", "Motors", JOptionPane.INFORMATION_MESSAGE);
            } else {
                
                boolean send = instance.agregarCaracteristicas(id, desc, maxVel, maxTorque, combustible, aceleracion, kilometraje, suspension, radiador);
                if (send != false) {
                    JOptionPane.showMessageDialog(null, "¡Se han agregado las caracteristicas!", "Motors", JOptionPane.INFORMATION_MESSAGE);
                    deshabilitar();
                    btnNew.setEnabled(true);
                }
            }
        } catch (Exception e) {
            System.out.println("LA VISTA DIJO: " + e.getMessage());
        }

    }

    private void limpiarYhabilitar() {

        txtId.setText(null);
        txtDescripcion.setText(null);
        txtVelMax.setText(null);
        txtMaxTorque.setText(null);
        txtCombustible.setText(null);
        txtAceleracion.setText(null);
        txtKilometraje.setText(null);
        txtSuspension.setText(null);
        txtRadiador.setText(null);

        txtId.setEnabled(true);
        txtDescripcion.setEnabled(true);
        txtVelMax.setEnabled(true);
        txtMaxTorque.setEnabled(true);
        txtCombustible.setEnabled(true);
        txtAceleracion.setEnabled(true);
        txtKilometraje.setEnabled(true);
        txtSuspension.setEnabled(true);
        txtRadiador.setEnabled(true);

    }

    private void deshabilitar() {
        txtId.setEnabled(false);
        txtDescripcion.setEnabled(false);
        txtVelMax.setEnabled(false);
        txtMaxTorque.setEnabled(false);
        txtCombustible.setEnabled(false);
        txtAceleracion.setEnabled(false);
        txtKilometraje.setEnabled(false);
        txtSuspension.setEnabled(false);
        txtRadiador.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSuspension = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtVelMax = new javax.swing.JTextField();
        txtMaxTorque = new javax.swing.JTextField();
        txtCombustible = new javax.swing.JTextField();
        txtAceleracion = new javax.swing.JTextField();
        txtKilometraje = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnAtras = new keeptoo.KButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtRadiador = new javax.swing.JTextField();
        btnNew = new keeptoo.KButton();
        btnAceptar = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(192, 190, 187));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(156, 167, 173));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("CONCESIONARIOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 18, -1, -1));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Motors &");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 40));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Asociados");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/img/miniLogoBlack.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 39, 33, 40));

        txtSuspension.setBackground(new java.awt.Color(102, 102, 102));
        txtSuspension.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtSuspension.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtSuspension, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 237, 35));

        txtId.setBackground(new java.awt.Color(102, 102, 102));
        txtId.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 237, 35));

        txtVelMax.setBackground(new java.awt.Color(102, 102, 102));
        txtVelMax.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtVelMax.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtVelMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 237, 35));

        txtMaxTorque.setBackground(new java.awt.Color(102, 102, 102));
        txtMaxTorque.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtMaxTorque.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtMaxTorque, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 237, 35));

        txtCombustible.setBackground(new java.awt.Color(102, 102, 102));
        txtCombustible.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtCombustible.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 237, 35));

        txtAceleracion.setBackground(new java.awt.Color(102, 102, 102));
        txtAceleracion.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtAceleracion.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtAceleracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 237, 35));

        txtKilometraje.setBackground(new java.awt.Color(102, 102, 102));
        txtKilometraje.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtKilometraje.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtKilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 237, 35));

        txtDescripcion.setBackground(new java.awt.Color(102, 102, 102));
        txtDescripcion.setColumns(20);
        txtDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 300, 90));

        btnAtras.setText("Atras");
        btnAtras.setBorderPainted(false);
        btnAtras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras.setIconTextGap(8);
        btnAtras.setkBackGroundColor(new java.awt.Color(136, 136, 136));
        btnAtras.setkEndColor(new java.awt.Color(136, 136, 136));
        btnAtras.setkHoverColor(new java.awt.Color(24, 25, 63));
        btnAtras.setkHoverEndColor(new java.awt.Color(136, 136, 136));
        btnAtras.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAtras.setkHoverStartColor(new java.awt.Color(14, 14, 14));
        btnAtras.setkPressedColor(new java.awt.Color(136, 136, 136));
        btnAtras.setkSelectedColor(new java.awt.Color(136, 136, 136));
        btnAtras.setkStartColor(new java.awt.Color(136, 136, 136));
        btnAtras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAtras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAtras.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 60, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Descripcion");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Velocidad Max");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Max Torque");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Tipo De Combustible");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Aceleracion");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Kilometraje");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Suspension");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Radiador");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        txtRadiador.setBackground(new java.awt.Color(102, 102, 102));
        txtRadiador.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtRadiador.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtRadiador, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 237, 35));

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnNew.setText("Nuevo");
        btnNew.setBorderPainted(false);
        btnNew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setIconTextGap(8);
        btnNew.setkBackGroundColor(new java.awt.Color(38, 39, 41));
        btnNew.setkEndColor(new java.awt.Color(0, 193, 56));
        btnNew.setkHoverColor(new java.awt.Color(24, 25, 63));
        btnNew.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnNew.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnNew.setkHoverStartColor(new java.awt.Color(14, 14, 14));
        btnNew.setkPressedColor(new java.awt.Color(24, 25, 63));
        btnNew.setkStartColor(new java.awt.Color(51, 102, 0));
        btnNew.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnNew.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnNew.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnNew.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel1.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 660, 138, -1));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorderPainted(false);
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptar.setIconTextGap(8);
        btnAceptar.setkBackGroundColor(new java.awt.Color(38, 39, 41));
        btnAceptar.setkEndColor(new java.awt.Color(0, 193, 56));
        btnAceptar.setkHoverColor(new java.awt.Color(24, 25, 63));
        btnAceptar.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnAceptar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAceptar.setkHoverStartColor(new java.awt.Color(14, 14, 14));
        btnAceptar.setkPressedColor(new java.awt.Color(24, 25, 63));
        btnAceptar.setkStartColor(new java.awt.Color(51, 102, 0));
        btnAceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 660, 138, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 720));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/img/vel.gif"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 680, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        main.irDashboard(this, cb);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        limpiarYhabilitar();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        add();
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnAceptar;
    private keeptoo.KButton btnAtras;
    private keeptoo.KButton btnNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAceleracion;
    private javax.swing.JTextField txtCombustible;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtKilometraje;
    private javax.swing.JTextField txtMaxTorque;
    private javax.swing.JTextField txtRadiador;
    private javax.swing.JTextField txtSuspension;
    private javax.swing.JTextField txtVelMax;
    // End of variables declaration//GEN-END:variables
}
