package com.portafolio.motors.ing.sis.proyecto.vista;

import com.portafolio.motors.ing.sis.proyecto.controlador.concesionarioBuilder;
import java.awt.Color;
import javax.swing.JPanel;
import keeptoo.Drag;

/**
 *
 * @author Yonier Asprilla
 */
public class Dashboard extends javax.swing.JPanel {
    
    private main main;
    private concesionarioBuilder cb;
    
    public Dashboard(main main, concesionarioBuilder cb) {
        this.main = main;
        this.cb = cb;
        initComponents();
        
    }
    
    void setColor(JPanel panel) { //227,225,231
        panel.setBackground(new Color(227, 225, 231));
    }
    
    void resetColor(JPanel panel) {//[247,245,249]
        panel.setBackground(new Color(247, 245, 249));
    }
    
    public void reset() {
        // PANELES
        pnlEmpleados.setVisible(false);
        pnlConcesionarios.setVisible(false);
        pnlOfertas.setVisible(false);
        pnlHome.setVisible(false);
        pnlFeatures.setVisible(false);
        pnlTaller.setVisible(false);
        pnlClientes.setVisible(false);
        // HOVERS
        resetColor(hoverHome);
        resetColor(hoverEMP);
        resetColor(hoverTaller);
        resetColor(hoverInventario);
        resetColor(hoverOfertas);
        resetColor(hoverClientes);
        resetColor(hoverPagos);
        resetColor(hoverCaracteristicas);
        resetColor(hoverSedes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlOfertas = new javax.swing.JPanel();
        pnlEmpleados = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        fSLabel1 = new LIB.FSLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanelRound6 = new LIB.JPanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        kButton6 = new keeptoo.KButton();
        jPanelRound7 = new LIB.JPanelRound();
        jLabel9 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnNuevosConcesionarios1 = new keeptoo.KButton();
        jPanelRound8 = new LIB.JPanelRound();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        btnModificarDatos1 = new keeptoo.KButton();
        jPanelRound9 = new LIB.JPanelRound();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        btnDesvincular1 = new keeptoo.KButton();
        jPanelRound10 = new LIB.JPanelRound();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btbBuscarConcesionarios1 = new keeptoo.KButton();
        pnlTaller = new javax.swing.JPanel();
        pnlConcesionarios = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanelRound1 = new LIB.JPanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        kButton5 = new keeptoo.KButton();
        jPanelRound2 = new LIB.JPanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        btnNuevosConcesionarios = new keeptoo.KButton();
        jPanelRound3 = new LIB.JPanelRound();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        btnModificarDatos = new keeptoo.KButton();
        jPanelRound4 = new LIB.JPanelRound();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        btnDesvincular = new keeptoo.KButton();
        jPanelRound5 = new LIB.JPanelRound();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btbBuscarConcesionarios = new keeptoo.KButton();
        jLabel18 = new javax.swing.JLabel();
        pnlFeatures = new javax.swing.JPanel();
        jPanelRound11 = new LIB.JPanelRound();
        jLabel32 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        btnNuevosConcesionarios2 = new keeptoo.KButton();
        pnlClientes = new javax.swing.JPanel();
        jPanelRound12 = new LIB.JPanelRound();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        kButton7 = new keeptoo.KButton();
        jPanelRound13 = new LIB.JPanelRound();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        btnNuevosConcesionarios3 = new keeptoo.KButton();
        jPanelRound14 = new LIB.JPanelRound();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        btnModificarDatos2 = new keeptoo.KButton();
        jPanelRound15 = new LIB.JPanelRound();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        btnDesvincular2 = new keeptoo.KButton();
        jPanelRound16 = new LIB.JPanelRound();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        btbBuscarConcesionarios2 = new keeptoo.KButton();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        hoverHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        btnHomes = new javax.swing.JLabel();
        hoverEMP = new javax.swing.JPanel();
        btnEmpleado = new javax.swing.JLabel();
        btnEmpleados = new javax.swing.JLabel();
        hoverTaller = new javax.swing.JPanel();
        btnTaller = new javax.swing.JLabel();
        btnMecanico = new javax.swing.JLabel();
        hoverInventario = new javax.swing.JPanel();
        btnInventarios = new javax.swing.JLabel();
        btnInventario = new javax.swing.JLabel();
        hoverOfertas = new javax.swing.JPanel();
        btnOffers = new javax.swing.JLabel();
        btnOfertas = new javax.swing.JLabel();
        hoverClientes = new javax.swing.JPanel();
        btnClients = new javax.swing.JLabel();
        btnClientes = new javax.swing.JLabel();
        hoverPagos = new javax.swing.JPanel();
        btnFpay = new javax.swing.JLabel();
        btnMediosPay = new javax.swing.JLabel();
        hoverCaracteristicas = new javax.swing.JPanel();
        btnCaract = new javax.swing.JLabel();
        btnAutos = new javax.swing.JLabel();
        hoverSedes = new javax.swing.JPanel();
        btnSede = new javax.swing.JLabel();
        btnConcesionarios = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 605));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        contenedor.add(pnlHome, "card6");

        pnlOfertas.setBackground(new java.awt.Color(255, 153, 153));
        pnlOfertas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        contenedor.add(pnlOfertas, "card3");

        pnlEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        pnlEmpleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/prb1.png"))); // NOI18N
        pnlEmpleados.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 540, 70, 70));

        fSLabel1.setBackground(new java.awt.Color(238, 238, 238));
        fSLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/userLog.png"))); // NOI18N
        fSLabel1.setText("");
        pnlEmpleados.add(fSLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, 30, 30));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/prb2.png"))); // NOI18N
        pnlEmpleados.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 70, 60));

        jPanelRound6.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound6.setColorPrimario(new java.awt.Color(96, 150, 150));
        jPanelRound6.setColorSecundario(new java.awt.Color(96, 150, 150));
        jPanelRound6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/img/btnwl.jpeg"))); // NOI18N
        jPanelRound6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 190, -1));

        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("la beinvenida");
        jPanelRound6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel24.setForeground(new java.awt.Color(204, 204, 204));
        jLabel24.setText("Te damos");
        jPanelRound6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        kButton6.setBorderPainted(false);
        kButton6.setkBackGroundColor(new java.awt.Color(96, 150, 150));
        kButton6.setkEndColor(new java.awt.Color(96, 150, 150));
        kButton6.setkForeGround(new java.awt.Color(96, 150, 150));
        kButton6.setkHoverColor(new java.awt.Color(96, 150, 150));
        kButton6.setkHoverEndColor(new java.awt.Color(96, 150, 150));
        kButton6.setkHoverForeGround(new java.awt.Color(96, 150, 150));
        kButton6.setkHoverStartColor(new java.awt.Color(96, 150, 150));
        kButton6.setkIndicatorColor(new java.awt.Color(96, 150, 150));
        kButton6.setkPressedColor(new java.awt.Color(96, 150, 150));
        kButton6.setkSelectedColor(new java.awt.Color(96, 150, 150));
        kButton6.setkStartColor(new java.awt.Color(96, 150, 150));
        jPanelRound6.add(kButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 80));

        pnlEmpleados.add(jPanelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 300, 80));

        jPanelRound7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Empleado");
        jPanelRound7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, -1));

        jLabel25.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Asociar");
        jPanelRound7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/userAdd.png"))); // NOI18N
        jPanelRound7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnNuevosConcesionarios1.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevosConcesionarios1.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevosConcesionarios1.setActionCommand("Asociar empleado");
        btnNuevosConcesionarios1.setBorderPainted(false);
        btnNuevosConcesionarios1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btnNuevosConcesionarios1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnNuevosConcesionarios1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnNuevosConcesionarios1.setIconTextGap(35);
        btnNuevosConcesionarios1.setkBackGroundColor(new java.awt.Color(242, 167, 81));
        btnNuevosConcesionarios1.setkEndColor(new java.awt.Color(242, 167, 81));
        btnNuevosConcesionarios1.setkForeGround(new java.awt.Color(0, 0, 0));
        btnNuevosConcesionarios1.setkHoverColor(new java.awt.Color(0, 193, 56));
        btnNuevosConcesionarios1.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnNuevosConcesionarios1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnNuevosConcesionarios1.setkHoverStartColor(new java.awt.Color(0, 193, 56));
        btnNuevosConcesionarios1.setkIndicatorColor(new java.awt.Color(51, 51, 51));
        btnNuevosConcesionarios1.setkStartColor(new java.awt.Color(242, 167, 81));
        btnNuevosConcesionarios1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnNuevosConcesionarios1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnNuevosConcesionarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevosConcesionarios1ActionPerformed(evt);
            }
        });
        jPanelRound7.add(btnNuevosConcesionarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));

        pnlEmpleados.add(jPanelRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 130, 130));

        jPanelRound8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Modificar");
        jPanelRound8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, -1));

        jLabel27.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Datos");
        jPanelRound8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/userModify.png"))); // NOI18N
        jPanelRound8.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnModificarDatos1.setBackground(new java.awt.Color(255, 255, 255));
        btnModificarDatos1.setForeground(new java.awt.Color(0, 0, 0));
        btnModificarDatos1.setActionCommand("Asociar empleado");
        btnModificarDatos1.setBorderPainted(false);
        btnModificarDatos1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btnModificarDatos1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnModificarDatos1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificarDatos1.setIconTextGap(8);
        btnModificarDatos1.setkBackGroundColor(new java.awt.Color(238, 172, 157));
        btnModificarDatos1.setkEndColor(new java.awt.Color(238, 172, 157));
        btnModificarDatos1.setkForeGround(new java.awt.Color(0, 0, 0));
        btnModificarDatos1.setkHoverColor(new java.awt.Color(0, 193, 56));
        btnModificarDatos1.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnModificarDatos1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnModificarDatos1.setkHoverStartColor(new java.awt.Color(0, 193, 56));
        btnModificarDatos1.setkIndicatorColor(new java.awt.Color(51, 51, 51));
        btnModificarDatos1.setkStartColor(new java.awt.Color(238, 172, 157));
        btnModificarDatos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDatos1ActionPerformed(evt);
            }
        });
        jPanelRound8.add(btnModificarDatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));

        pnlEmpleados.add(jPanelRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 130, 130));

        jPanelRound9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Empleado");
        jPanelRound9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel29.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Desvincular");
        jPanelRound9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/userDeleted.png"))); // NOI18N
        jPanelRound9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnDesvincular1.setBackground(new java.awt.Color(255, 255, 255));
        btnDesvincular1.setForeground(new java.awt.Color(0, 0, 0));
        btnDesvincular1.setToolTipText("");
        btnDesvincular1.setActionCommand("Asociar empleado");
        btnDesvincular1.setBorderPainted(false);
        btnDesvincular1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btnDesvincular1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDesvincular1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDesvincular1.setIconTextGap(7);
        btnDesvincular1.setkBackGroundColor(new java.awt.Color(45, 46, 70));
        btnDesvincular1.setkEndColor(new java.awt.Color(45, 46, 70));
        btnDesvincular1.setkForeGround(new java.awt.Color(0, 0, 0));
        btnDesvincular1.setkHoverColor(new java.awt.Color(0, 193, 56));
        btnDesvincular1.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnDesvincular1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDesvincular1.setkHoverStartColor(new java.awt.Color(0, 193, 56));
        btnDesvincular1.setkIndicatorColor(new java.awt.Color(51, 51, 51));
        btnDesvincular1.setkStartColor(new java.awt.Color(45, 46, 70));
        btnDesvincular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesvincular1ActionPerformed(evt);
            }
        });
        jPanelRound9.add(btnDesvincular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));

        pnlEmpleados.add(jPanelRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 130, 130));

        jPanelRound10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Empleado");
        jPanelRound10.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel31.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Buscar");
        jPanelRound10.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/searching.png"))); // NOI18N
        jPanelRound10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btbBuscarConcesionarios1.setBackground(new java.awt.Color(255, 255, 255));
        btbBuscarConcesionarios1.setForeground(new java.awt.Color(0, 0, 0));
        btbBuscarConcesionarios1.setActionCommand("Asociar empleado");
        btbBuscarConcesionarios1.setBorderPainted(false);
        btbBuscarConcesionarios1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btbBuscarConcesionarios1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btbBuscarConcesionarios1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btbBuscarConcesionarios1.setIconTextGap(8);
        btbBuscarConcesionarios1.setkBackGroundColor(new java.awt.Color(242, 167, 81));
        btbBuscarConcesionarios1.setkEndColor(new java.awt.Color(242, 167, 81));
        btbBuscarConcesionarios1.setkForeGround(new java.awt.Color(0, 0, 0));
        btbBuscarConcesionarios1.setkHoverColor(new java.awt.Color(0, 193, 56));
        btbBuscarConcesionarios1.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btbBuscarConcesionarios1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btbBuscarConcesionarios1.setkHoverStartColor(new java.awt.Color(0, 193, 56));
        btbBuscarConcesionarios1.setkIndicatorColor(new java.awt.Color(51, 51, 51));
        btbBuscarConcesionarios1.setkStartColor(new java.awt.Color(242, 167, 81));
        btbBuscarConcesionarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbBuscarConcesionarios1ActionPerformed(evt);
            }
        });
        jPanelRound10.add(btbBuscarConcesionarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));

        pnlEmpleados.add(jPanelRound10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 130, 130));

        contenedor.add(pnlEmpleados, "card4");

        javax.swing.GroupLayout pnlTallerLayout = new javax.swing.GroupLayout(pnlTaller);
        pnlTaller.setLayout(pnlTallerLayout);
        pnlTallerLayout.setHorizontalGroup(
            pnlTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        pnlTallerLayout.setVerticalGroup(
            pnlTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        contenedor.add(pnlTaller, "card5");

        pnlConcesionarios.setBackground(new java.awt.Color(255, 255, 255));
        pnlConcesionarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/prb2.png"))); // NOI18N
        pnlConcesionarios.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 60, 60));

        jPanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound1.setColorPrimario(new java.awt.Color(96, 150, 150));
        jPanelRound1.setColorSecundario(new java.awt.Color(96, 150, 150));
        jPanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/img/btnwl.jpeg"))); // NOI18N
        jPanelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 190, -1));

        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("la beinvenida");
        jPanelRound1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Te damos");
        jPanelRound1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        kButton5.setBorderPainted(false);
        kButton5.setkBackGroundColor(new java.awt.Color(96, 150, 150));
        kButton5.setkEndColor(new java.awt.Color(96, 150, 150));
        kButton5.setkForeGround(new java.awt.Color(96, 150, 150));
        kButton5.setkHoverColor(new java.awt.Color(96, 150, 150));
        kButton5.setkHoverEndColor(new java.awt.Color(96, 150, 150));
        kButton5.setkHoverForeGround(new java.awt.Color(96, 150, 150));
        kButton5.setkHoverStartColor(new java.awt.Color(96, 150, 150));
        kButton5.setkIndicatorColor(new java.awt.Color(96, 150, 150));
        kButton5.setkPressedColor(new java.awt.Color(96, 150, 150));
        kButton5.setkSelectedColor(new java.awt.Color(96, 150, 150));
        kButton5.setkStartColor(new java.awt.Color(96, 150, 150));
        jPanelRound1.add(kButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 80));

        pnlConcesionarios.add(jPanelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 300, 80));

        jPanelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Concesionario");
        jPanelRound2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nuevo");
        jPanelRound2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/bookWhite.png"))); // NOI18N
        jLabel36.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelRound2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnNuevosConcesionarios.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevosConcesionarios.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevosConcesionarios.setActionCommand("Asociar empleado");
        btnNuevosConcesionarios.setBorderPainted(false);
        btnNuevosConcesionarios.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btnNuevosConcesionarios.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnNuevosConcesionarios.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnNuevosConcesionarios.setIconTextGap(35);
        btnNuevosConcesionarios.setkBackGroundColor(new java.awt.Color(242, 167, 81));
        btnNuevosConcesionarios.setkEndColor(new java.awt.Color(242, 167, 81));
        btnNuevosConcesionarios.setkForeGround(new java.awt.Color(0, 0, 0));
        btnNuevosConcesionarios.setkHoverColor(new java.awt.Color(0, 193, 56));
        btnNuevosConcesionarios.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnNuevosConcesionarios.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnNuevosConcesionarios.setkHoverStartColor(new java.awt.Color(0, 193, 56));
        btnNuevosConcesionarios.setkIndicatorColor(new java.awt.Color(51, 51, 51));
        btnNuevosConcesionarios.setkStartColor(new java.awt.Color(242, 167, 81));
        btnNuevosConcesionarios.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnNuevosConcesionarios.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnNuevosConcesionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevosConcesionariosActionPerformed(evt);
            }
        });
        jPanelRound2.add(btnNuevosConcesionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));

        pnlConcesionarios.add(jPanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 130, 130));

        jPanelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Modificar");
        jPanelRound3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Concesionario");
        jPanelRound3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/modify.png"))); // NOI18N
        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelRound3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnModificarDatos.setBackground(new java.awt.Color(255, 255, 255));
        btnModificarDatos.setForeground(new java.awt.Color(0, 0, 0));
        btnModificarDatos.setActionCommand("Asociar empleado");
        btnModificarDatos.setBorderPainted(false);
        btnModificarDatos.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btnModificarDatos.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnModificarDatos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificarDatos.setIconTextGap(8);
        btnModificarDatos.setkBackGroundColor(new java.awt.Color(238, 172, 157));
        btnModificarDatos.setkEndColor(new java.awt.Color(238, 172, 157));
        btnModificarDatos.setkForeGround(new java.awt.Color(0, 0, 0));
        btnModificarDatos.setkHoverColor(new java.awt.Color(0, 193, 56));
        btnModificarDatos.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnModificarDatos.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnModificarDatos.setkHoverStartColor(new java.awt.Color(0, 193, 56));
        btnModificarDatos.setkIndicatorColor(new java.awt.Color(51, 51, 51));
        btnModificarDatos.setkStartColor(new java.awt.Color(238, 172, 157));
        btnModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDatosActionPerformed(evt);
            }
        });
        jPanelRound3.add(btnModificarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));

        pnlConcesionarios.add(jPanelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 130, 130));

        jPanelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Concesionario");
        jPanelRound4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Desvincular");
        jPanelRound4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/whiTrash.png"))); // NOI18N
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelRound4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        btnDesvincular.setBackground(new java.awt.Color(255, 255, 255));
        btnDesvincular.setForeground(new java.awt.Color(0, 0, 0));
        btnDesvincular.setToolTipText("");
        btnDesvincular.setActionCommand("Asociar empleado");
        btnDesvincular.setBorderPainted(false);
        btnDesvincular.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btnDesvincular.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDesvincular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDesvincular.setIconTextGap(7);
        btnDesvincular.setkBackGroundColor(new java.awt.Color(45, 46, 70));
        btnDesvincular.setkEndColor(new java.awt.Color(45, 46, 70));
        btnDesvincular.setkForeGround(new java.awt.Color(0, 0, 0));
        btnDesvincular.setkHoverColor(new java.awt.Color(0, 193, 56));
        btnDesvincular.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnDesvincular.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDesvincular.setkHoverStartColor(new java.awt.Color(0, 193, 56));
        btnDesvincular.setkIndicatorColor(new java.awt.Color(51, 51, 51));
        btnDesvincular.setkStartColor(new java.awt.Color(45, 46, 70));
        btnDesvincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesvincularActionPerformed(evt);
            }
        });
        jPanelRound4.add(btnDesvincular, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));

        pnlConcesionarios.add(jPanelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 130, 130));

        jPanelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Concesionario");
        jPanelRound5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel19.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Buscar");
        jPanelRound5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/searching.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelRound5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btbBuscarConcesionarios.setBackground(new java.awt.Color(255, 255, 255));
        btbBuscarConcesionarios.setForeground(new java.awt.Color(0, 0, 0));
        btbBuscarConcesionarios.setActionCommand("Asociar empleado");
        btbBuscarConcesionarios.setBorderPainted(false);
        btbBuscarConcesionarios.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btbBuscarConcesionarios.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btbBuscarConcesionarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btbBuscarConcesionarios.setIconTextGap(8);
        btbBuscarConcesionarios.setkBackGroundColor(new java.awt.Color(242, 167, 81));
        btbBuscarConcesionarios.setkEndColor(new java.awt.Color(242, 167, 81));
        btbBuscarConcesionarios.setkForeGround(new java.awt.Color(0, 0, 0));
        btbBuscarConcesionarios.setkHoverColor(new java.awt.Color(0, 193, 56));
        btbBuscarConcesionarios.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btbBuscarConcesionarios.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btbBuscarConcesionarios.setkHoverStartColor(new java.awt.Color(0, 193, 56));
        btbBuscarConcesionarios.setkIndicatorColor(new java.awt.Color(51, 51, 51));
        btbBuscarConcesionarios.setkStartColor(new java.awt.Color(242, 167, 81));
        btbBuscarConcesionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbBuscarConcesionariosActionPerformed(evt);
            }
        });
        jPanelRound5.add(btbBuscarConcesionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));

        pnlConcesionarios.add(jPanelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 130, 130));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/prb1.png"))); // NOI18N
        pnlConcesionarios.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 540, 70, 70));

        contenedor.add(pnlConcesionarios, "card2");

        pnlFeatures.setBackground(new java.awt.Color(255, 255, 255));
        pnlFeatures.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRound11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Concesionario");
        jPanelRound11.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, -1));

        jLabel39.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Nuevo");
        jPanelRound11.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/bookWhite.png"))); // NOI18N
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelRound11.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnNuevosConcesionarios2.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevosConcesionarios2.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevosConcesionarios2.setActionCommand("Asociar empleado");
        btnNuevosConcesionarios2.setBorderPainted(false);
        btnNuevosConcesionarios2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btnNuevosConcesionarios2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnNuevosConcesionarios2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnNuevosConcesionarios2.setIconTextGap(35);
        btnNuevosConcesionarios2.setkBackGroundColor(new java.awt.Color(242, 167, 81));
        btnNuevosConcesionarios2.setkEndColor(new java.awt.Color(242, 167, 81));
        btnNuevosConcesionarios2.setkForeGround(new java.awt.Color(0, 0, 0));
        btnNuevosConcesionarios2.setkHoverColor(new java.awt.Color(0, 193, 56));
        btnNuevosConcesionarios2.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnNuevosConcesionarios2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnNuevosConcesionarios2.setkHoverStartColor(new java.awt.Color(0, 193, 56));
        btnNuevosConcesionarios2.setkIndicatorColor(new java.awt.Color(51, 51, 51));
        btnNuevosConcesionarios2.setkStartColor(new java.awt.Color(242, 167, 81));
        btnNuevosConcesionarios2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnNuevosConcesionarios2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnNuevosConcesionarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevosConcesionarios2ActionPerformed(evt);
            }
        });
        jPanelRound11.add(btnNuevosConcesionarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));

        pnlFeatures.add(jPanelRound11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 130, 130));

        contenedor.add(pnlFeatures, "card7");

        pnlClientes.setBackground(new java.awt.Color(255, 255, 255));
        pnlClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRound12.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound12.setColorPrimario(new java.awt.Color(96, 150, 150));
        jPanelRound12.setColorSecundario(new java.awt.Color(96, 150, 150));
        jPanelRound12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/img/btnwl.jpeg"))); // NOI18N
        jPanelRound12.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 190, -1));

        jLabel42.setForeground(new java.awt.Color(204, 204, 204));
        jLabel42.setText("la beinvenida");
        jPanelRound12.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel43.setForeground(new java.awt.Color(204, 204, 204));
        jLabel43.setText("Te damos");
        jPanelRound12.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        kButton7.setBorderPainted(false);
        kButton7.setkBackGroundColor(new java.awt.Color(96, 150, 150));
        kButton7.setkEndColor(new java.awt.Color(96, 150, 150));
        kButton7.setkForeGround(new java.awt.Color(96, 150, 150));
        kButton7.setkHoverColor(new java.awt.Color(96, 150, 150));
        kButton7.setkHoverEndColor(new java.awt.Color(96, 150, 150));
        kButton7.setkHoverForeGround(new java.awt.Color(96, 150, 150));
        kButton7.setkHoverStartColor(new java.awt.Color(96, 150, 150));
        kButton7.setkIndicatorColor(new java.awt.Color(96, 150, 150));
        kButton7.setkPressedColor(new java.awt.Color(96, 150, 150));
        kButton7.setkSelectedColor(new java.awt.Color(96, 150, 150));
        kButton7.setkStartColor(new java.awt.Color(96, 150, 150));
        jPanelRound12.add(kButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 80));

        pnlClientes.add(jPanelRound12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 300, 80));

        jPanelRound13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Cliente");
        jPanelRound13.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, -1));

        jLabel45.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Asociar");
        jPanelRound13.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, -1));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/userAdd.png"))); // NOI18N
        jPanelRound13.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnNuevosConcesionarios3.setBackground(new java.awt.Color(255, 255, 255));
        btnNuevosConcesionarios3.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevosConcesionarios3.setActionCommand("Asociar empleado");
        btnNuevosConcesionarios3.setBorderPainted(false);
        btnNuevosConcesionarios3.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btnNuevosConcesionarios3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnNuevosConcesionarios3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnNuevosConcesionarios3.setIconTextGap(35);
        btnNuevosConcesionarios3.setkBackGroundColor(new java.awt.Color(242, 167, 81));
        btnNuevosConcesionarios3.setkEndColor(new java.awt.Color(242, 167, 81));
        btnNuevosConcesionarios3.setkForeGround(new java.awt.Color(0, 0, 0));
        btnNuevosConcesionarios3.setkHoverColor(new java.awt.Color(0, 193, 56));
        btnNuevosConcesionarios3.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnNuevosConcesionarios3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnNuevosConcesionarios3.setkHoverStartColor(new java.awt.Color(0, 193, 56));
        btnNuevosConcesionarios3.setkIndicatorColor(new java.awt.Color(51, 51, 51));
        btnNuevosConcesionarios3.setkStartColor(new java.awt.Color(242, 167, 81));
        btnNuevosConcesionarios3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnNuevosConcesionarios3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnNuevosConcesionarios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevosConcesionarios3ActionPerformed(evt);
            }
        });
        jPanelRound13.add(btnNuevosConcesionarios3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));

        pnlClientes.add(jPanelRound13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 130, 130));

        jPanelRound14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Modificar");
        jPanelRound14.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, -1));

        jLabel48.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Datos");
        jPanelRound14.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 120, -1));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/userModify.png"))); // NOI18N
        jPanelRound14.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnModificarDatos2.setBackground(new java.awt.Color(255, 255, 255));
        btnModificarDatos2.setForeground(new java.awt.Color(0, 0, 0));
        btnModificarDatos2.setActionCommand("Asociar empleado");
        btnModificarDatos2.setBorderPainted(false);
        btnModificarDatos2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btnModificarDatos2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnModificarDatos2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificarDatos2.setIconTextGap(8);
        btnModificarDatos2.setkBackGroundColor(new java.awt.Color(238, 172, 157));
        btnModificarDatos2.setkEndColor(new java.awt.Color(238, 172, 157));
        btnModificarDatos2.setkForeGround(new java.awt.Color(0, 0, 0));
        btnModificarDatos2.setkHoverColor(new java.awt.Color(0, 193, 56));
        btnModificarDatos2.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnModificarDatos2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnModificarDatos2.setkHoverStartColor(new java.awt.Color(0, 193, 56));
        btnModificarDatos2.setkIndicatorColor(new java.awt.Color(51, 51, 51));
        btnModificarDatos2.setkStartColor(new java.awt.Color(238, 172, 157));
        btnModificarDatos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDatos2ActionPerformed(evt);
            }
        });
        jPanelRound14.add(btnModificarDatos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));

        pnlClientes.add(jPanelRound14, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 130, 130));

        jPanelRound15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Cliente");
        jPanelRound15.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel51.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Desvincular");
        jPanelRound15.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/userDeleted.png"))); // NOI18N
        jPanelRound15.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnDesvincular2.setBackground(new java.awt.Color(255, 255, 255));
        btnDesvincular2.setForeground(new java.awt.Color(0, 0, 0));
        btnDesvincular2.setToolTipText("");
        btnDesvincular2.setActionCommand("Asociar empleado");
        btnDesvincular2.setBorderPainted(false);
        btnDesvincular2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btnDesvincular2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnDesvincular2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDesvincular2.setIconTextGap(7);
        btnDesvincular2.setkBackGroundColor(new java.awt.Color(45, 46, 70));
        btnDesvincular2.setkEndColor(new java.awt.Color(45, 46, 70));
        btnDesvincular2.setkForeGround(new java.awt.Color(0, 0, 0));
        btnDesvincular2.setkHoverColor(new java.awt.Color(0, 193, 56));
        btnDesvincular2.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnDesvincular2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDesvincular2.setkHoverStartColor(new java.awt.Color(0, 193, 56));
        btnDesvincular2.setkIndicatorColor(new java.awt.Color(51, 51, 51));
        btnDesvincular2.setkStartColor(new java.awt.Color(45, 46, 70));
        btnDesvincular2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesvincular2ActionPerformed(evt);
            }
        });
        jPanelRound15.add(btnDesvincular2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));

        pnlClientes.add(jPanelRound15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 130, 130));

        jPanelRound16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Datos");
        jPanelRound16.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel54.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Buscar");
        jPanelRound16.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/searching.png"))); // NOI18N
        jPanelRound16.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btbBuscarConcesionarios2.setBackground(new java.awt.Color(255, 255, 255));
        btbBuscarConcesionarios2.setForeground(new java.awt.Color(0, 0, 0));
        btbBuscarConcesionarios2.setActionCommand("Asociar empleado");
        btbBuscarConcesionarios2.setBorderPainted(false);
        btbBuscarConcesionarios2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        btbBuscarConcesionarios2.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btbBuscarConcesionarios2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btbBuscarConcesionarios2.setIconTextGap(8);
        btbBuscarConcesionarios2.setkBackGroundColor(new java.awt.Color(242, 167, 81));
        btbBuscarConcesionarios2.setkEndColor(new java.awt.Color(242, 167, 81));
        btbBuscarConcesionarios2.setkForeGround(new java.awt.Color(0, 0, 0));
        btbBuscarConcesionarios2.setkHoverColor(new java.awt.Color(0, 193, 56));
        btbBuscarConcesionarios2.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btbBuscarConcesionarios2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btbBuscarConcesionarios2.setkHoverStartColor(new java.awt.Color(0, 193, 56));
        btbBuscarConcesionarios2.setkIndicatorColor(new java.awt.Color(51, 51, 51));
        btbBuscarConcesionarios2.setkStartColor(new java.awt.Color(242, 167, 81));
        btbBuscarConcesionarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbBuscarConcesionarios2ActionPerformed(evt);
            }
        });
        jPanelRound16.add(btbBuscarConcesionarios2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 130));

        pnlClientes.add(jPanelRound16, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 130, 130));

        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/prb2.png"))); // NOI18N
        pnlClientes.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 70, 60));

        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/prb1.png"))); // NOI18N
        pnlClientes.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 540, 70, 70));

        contenedor.add(pnlClientes, "card8");

        add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 1170, 610));

        jPanel1.setBackground(new java.awt.Color(247, 245, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/img/miniLogo.png"))); // NOI18N
        jLabel20.setText("| Motors");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 204, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("•");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 20, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("•");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        hoverHome.setBackground(new java.awt.Color(227, 225, 231));

        btnHome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/homeGray2.png"))); // NOI18N
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnHomes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnHomes.setForeground(new java.awt.Color(153, 153, 153));
        btnHomes.setText("Home");
        btnHomes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hoverHomeLayout = new javax.swing.GroupLayout(hoverHome);
        hoverHome.setLayout(hoverHomeLayout);
        hoverHomeLayout.setHorizontalGroup(
            hoverHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHomes, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
        );
        hoverHomeLayout.setVerticalGroup(
            hoverHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(hoverHomeLayout.createSequentialGroup()
                .addComponent(btnHomes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(hoverHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 30));

        hoverEMP.setBackground(new java.awt.Color(247, 245, 249));

        btnEmpleado.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEmpleado.setForeground(new java.awt.Color(153, 153, 153));
        btnEmpleado.setText("Empleados");
        btnEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseClicked(evt);
            }
        });

        btnEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usersGray2.png"))); // NOI18N
        btnEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmpleadosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hoverEMPLayout = new javax.swing.GroupLayout(hoverEMP);
        hoverEMP.setLayout(hoverEMPLayout);
        hoverEMPLayout.setHorizontalGroup(
            hoverEMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverEMPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );
        hoverEMPLayout.setVerticalGroup(
            hoverEMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEmpleados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jPanel1.add(hoverEMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, -1));

        hoverTaller.setBackground(new java.awt.Color(247, 245, 249));

        btnTaller.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTaller.setForeground(new java.awt.Color(153, 153, 153));
        btnTaller.setText("Taller");
        btnTaller.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTaller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTallerMouseClicked(evt);
            }
        });

        btnMecanico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMecanico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/tallerGrat3.png"))); // NOI18N
        btnMecanico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout hoverTallerLayout = new javax.swing.GroupLayout(hoverTaller);
        hoverTaller.setLayout(hoverTallerLayout);
        hoverTallerLayout.setHorizontalGroup(
            hoverTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverTallerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTaller, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
        );
        hoverTallerLayout.setVerticalGroup(
            hoverTallerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTaller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMecanico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jPanel1.add(hoverTaller, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        hoverInventario.setBackground(new java.awt.Color(247, 245, 249));

        btnInventarios.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnInventarios.setForeground(new java.awt.Color(153, 153, 153));
        btnInventarios.setText("Inventarios");
        btnInventarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInventarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInventariosMouseClicked(evt);
            }
        });

        btnInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/inventoryGray2.png"))); // NOI18N
        btnInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout hoverInventarioLayout = new javax.swing.GroupLayout(hoverInventario);
        hoverInventario.setLayout(hoverInventarioLayout);
        hoverInventarioLayout.setHorizontalGroup(
            hoverInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverInventarioLayout.createSequentialGroup()
                .addComponent(btnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInventarios, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
        );
        hoverInventarioLayout.setVerticalGroup(
            hoverInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInventarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnInventario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jPanel1.add(hoverInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        hoverOfertas.setBackground(new java.awt.Color(247, 245, 249));

        btnOffers.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnOffers.setForeground(new java.awt.Color(153, 153, 153));
        btnOffers.setText("Ofertas");
        btnOffers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOffers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOffersMouseClicked(evt);
            }
        });

        btnOfertas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnOfertas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/saleGray2.png"))); // NOI18N
        btnOfertas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout hoverOfertasLayout = new javax.swing.GroupLayout(hoverOfertas);
        hoverOfertas.setLayout(hoverOfertasLayout);
        hoverOfertasLayout.setHorizontalGroup(
            hoverOfertasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverOfertasLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnOfertas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOffers, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
        );
        hoverOfertasLayout.setVerticalGroup(
            hoverOfertasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnOffers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnOfertas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jPanel1.add(hoverOfertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        hoverClientes.setBackground(new java.awt.Color(247, 245, 249));

        btnClients.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnClients.setForeground(new java.awt.Color(153, 153, 153));
        btnClients.setText("Clientes");
        btnClients.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientsMouseClicked(evt);
            }
        });

        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/clientGray2.png"))); // NOI18N
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout hoverClientesLayout = new javax.swing.GroupLayout(hoverClientes);
        hoverClientes.setLayout(hoverClientesLayout);
        hoverClientesLayout.setHorizontalGroup(
            hoverClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverClientesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClients, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
        );
        hoverClientesLayout.setVerticalGroup(
            hoverClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jPanel1.add(hoverClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        hoverPagos.setBackground(new java.awt.Color(247, 245, 249));

        btnFpay.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnFpay.setForeground(new java.awt.Color(153, 153, 153));
        btnFpay.setText("F. de pago");
        btnFpay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFpay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFpayMouseClicked(evt);
            }
        });

        btnMediosPay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMediosPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/payGray2.png"))); // NOI18N
        btnMediosPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout hoverPagosLayout = new javax.swing.GroupLayout(hoverPagos);
        hoverPagos.setLayout(hoverPagosLayout);
        hoverPagosLayout.setHorizontalGroup(
            hoverPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverPagosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnMediosPay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFpay, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        hoverPagosLayout.setVerticalGroup(
            hoverPagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFpay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMediosPay, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jPanel1.add(hoverPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        hoverCaracteristicas.setBackground(new java.awt.Color(247, 245, 249));

        btnCaract.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCaract.setForeground(new java.awt.Color(153, 153, 153));
        btnCaract.setText("Caracteristicas");
        btnCaract.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCaract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCaractMouseClicked(evt);
            }
        });

        btnAutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/characteristGray2.png"))); // NOI18N
        btnAutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout hoverCaracteristicasLayout = new javax.swing.GroupLayout(hoverCaracteristicas);
        hoverCaracteristicas.setLayout(hoverCaracteristicasLayout);
        hoverCaracteristicasLayout.setHorizontalGroup(
            hoverCaracteristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverCaracteristicasLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCaract, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
        );
        hoverCaracteristicasLayout.setVerticalGroup(
            hoverCaracteristicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCaract, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAutos, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jPanel1.add(hoverCaracteristicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        hoverSedes.setBackground(new java.awt.Color(247, 245, 249));

        btnSede.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSede.setForeground(new java.awt.Color(153, 153, 153));
        btnSede.setText("Sedes");
        btnSede.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSedeMouseClicked(evt);
            }
        });

        btnConcesionarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConcesionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/shopGray2.png"))); // NOI18N
        btnConcesionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConcesionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConcesionariosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hoverSedesLayout = new javax.swing.GroupLayout(hoverSedes);
        hoverSedes.setLayout(hoverSedesLayout);
        hoverSedesLayout.setHorizontalGroup(
            hoverSedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverSedesLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnConcesionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSede, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
        );
        hoverSedesLayout.setVerticalGroup(
            hoverSedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnConcesionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        jPanel1.add(hoverSedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked

    }//GEN-LAST:event_jLabel11MouseClicked

    private void btnEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadosMouseClicked
        reset();
        setColor(hoverEMP);
        pnlEmpleados.setVisible(true);
        

    }//GEN-LAST:event_btnEmpleadosMouseClicked

    private void btnConcesionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConcesionariosMouseClicked
        reset();
        setColor(hoverSedes);
        pnlConcesionarios.setVisible(true);
        

    }//GEN-LAST:event_btnConcesionariosMouseClicked

    private void btnNuevosConcesionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevosConcesionariosActionPerformed
        main.irNewconcessionaire(this, cb);
    }//GEN-LAST:event_btnNuevosConcesionariosActionPerformed

    private void btbBuscarConcesionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbBuscarConcesionariosActionPerformed
        main.irShowConcessionaire(this, cb);
    }//GEN-LAST:event_btbBuscarConcesionariosActionPerformed

    private void btnHomesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomesMouseClicked
        reset();
        setColor(hoverHome);

    }//GEN-LAST:event_btnHomesMouseClicked

    private void btnEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadoMouseClicked
        reset();
        setColor(hoverEMP);
        //Show panel
        pnlEmpleados.setVisible(true);
    }//GEN-LAST:event_btnEmpleadoMouseClicked

    private void btnTallerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTallerMouseClicked
        reset();
        setColor(hoverTaller);
        //show panel
        pnlTaller.setVisible(true);
    }//GEN-LAST:event_btnTallerMouseClicked

    private void btnInventariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInventariosMouseClicked
        reset();
        setColor(hoverInventario);
        //show panel


    }//GEN-LAST:event_btnInventariosMouseClicked

    private void btnOffersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOffersMouseClicked
        reset();
        setColor(hoverOfertas);
        //show panel
        pnlOfertas.setVisible(true);
    }//GEN-LAST:event_btnOffersMouseClicked

    private void btnClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientsMouseClicked
        reset();
        setColor(hoverClientes);
        pnlClientes.setVisible(true);
    }//GEN-LAST:event_btnClientsMouseClicked

    private void btnFpayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFpayMouseClicked
        reset();
        setColor(hoverPagos);

    }//GEN-LAST:event_btnFpayMouseClicked

    private void btnCaractMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCaractMouseClicked
        reset();
        setColor(hoverCaracteristicas);
        pnlFeatures.setVisible(true);
    }//GEN-LAST:event_btnCaractMouseClicked

    private void btnSedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSedeMouseClicked
        reset();
        setColor(hoverSedes);
        //show panel
        pnlConcesionarios.setVisible(true);
    }//GEN-LAST:event_btnSedeMouseClicked

    private void btnModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDatosActionPerformed
        main.irModifyConcessionaire(this, cb);
    }//GEN-LAST:event_btnModificarDatosActionPerformed

    private void btnNuevosConcesionarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevosConcesionarios1ActionPerformed
        //main.irNewEmployee(this);
        main.irNewconcessionaire(this, cb);
    }//GEN-LAST:event_btnNuevosConcesionarios1ActionPerformed

    private void btnModificarDatos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDatos1ActionPerformed
        main.irModifyConcessionaire(this, cb);
    }//GEN-LAST:event_btnModificarDatos1ActionPerformed

    private void btbBuscarConcesionarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbBuscarConcesionarios1ActionPerformed
        main.irShowConcessionaire(this, cb);
    }//GEN-LAST:event_btbBuscarConcesionarios1ActionPerformed

    private void btnNuevosConcesionarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevosConcesionarios2ActionPerformed
        //main.irAddFeatures(this);
    }//GEN-LAST:event_btnNuevosConcesionarios2ActionPerformed

    private void btnDesvincular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesvincular1ActionPerformed
        //new alertas.AlertInformation(main, true).setVisible(true);
    }//GEN-LAST:event_btnDesvincular1ActionPerformed

    private void btnDesvincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesvincularActionPerformed
        main.irShowConcessionaire(this, cb);
    }//GEN-LAST:event_btnDesvincularActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        new keeptoo.Drag(jPanel1).moveWindow(evt);
        new keeptoo.Drag(contenedor).moveWindow(evt);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        new keeptoo.Drag(jPanel1).onPress(evt);
        new keeptoo.Drag(contenedor).onPress(evt);
    }//GEN-LAST:event_formMousePressed

    private void btnNuevosConcesionarios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevosConcesionarios3ActionPerformed
        main.irNewClient(this);
    }//GEN-LAST:event_btnNuevosConcesionarios3ActionPerformed

    private void btnModificarDatos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDatos2ActionPerformed

    }//GEN-LAST:event_btnModificarDatos2ActionPerformed

    private void btnDesvincular2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesvincular2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDesvincular2ActionPerformed

    private void btbBuscarConcesionarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbBuscarConcesionarios2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbBuscarConcesionarios2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btbBuscarConcesionarios;
    private keeptoo.KButton btbBuscarConcesionarios1;
    private keeptoo.KButton btbBuscarConcesionarios2;
    private javax.swing.JLabel btnAutos;
    private javax.swing.JLabel btnCaract;
    private javax.swing.JLabel btnClientes;
    private javax.swing.JLabel btnClients;
    private javax.swing.JLabel btnConcesionarios;
    private keeptoo.KButton btnDesvincular;
    private keeptoo.KButton btnDesvincular1;
    private keeptoo.KButton btnDesvincular2;
    private javax.swing.JLabel btnEmpleado;
    private javax.swing.JLabel btnEmpleados;
    private javax.swing.JLabel btnFpay;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnHomes;
    private javax.swing.JLabel btnInventario;
    private javax.swing.JLabel btnInventarios;
    private javax.swing.JLabel btnMecanico;
    private javax.swing.JLabel btnMediosPay;
    private keeptoo.KButton btnModificarDatos;
    private keeptoo.KButton btnModificarDatos1;
    private keeptoo.KButton btnModificarDatos2;
    private keeptoo.KButton btnNuevosConcesionarios;
    private keeptoo.KButton btnNuevosConcesionarios1;
    private keeptoo.KButton btnNuevosConcesionarios2;
    private keeptoo.KButton btnNuevosConcesionarios3;
    private javax.swing.JLabel btnOfertas;
    private javax.swing.JLabel btnOffers;
    private javax.swing.JLabel btnSede;
    private javax.swing.JLabel btnTaller;
    private javax.swing.JPanel contenedor;
    private LIB.FSLabel fSLabel1;
    private javax.swing.JPanel hoverCaracteristicas;
    private javax.swing.JPanel hoverClientes;
    private javax.swing.JPanel hoverEMP;
    private javax.swing.JPanel hoverHome;
    private javax.swing.JPanel hoverInventario;
    private javax.swing.JPanel hoverOfertas;
    private javax.swing.JPanel hoverPagos;
    private javax.swing.JPanel hoverSedes;
    private javax.swing.JPanel hoverTaller;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private LIB.JPanelRound jPanelRound1;
    private LIB.JPanelRound jPanelRound10;
    private LIB.JPanelRound jPanelRound11;
    private LIB.JPanelRound jPanelRound12;
    private LIB.JPanelRound jPanelRound13;
    private LIB.JPanelRound jPanelRound14;
    private LIB.JPanelRound jPanelRound15;
    private LIB.JPanelRound jPanelRound16;
    private LIB.JPanelRound jPanelRound2;
    private LIB.JPanelRound jPanelRound3;
    private LIB.JPanelRound jPanelRound4;
    private LIB.JPanelRound jPanelRound5;
    private LIB.JPanelRound jPanelRound6;
    private LIB.JPanelRound jPanelRound7;
    private LIB.JPanelRound jPanelRound8;
    private LIB.JPanelRound jPanelRound9;
    private keeptoo.KButton kButton5;
    private keeptoo.KButton kButton6;
    private keeptoo.KButton kButton7;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlConcesionarios;
    private javax.swing.JPanel pnlEmpleados;
    private javax.swing.JPanel pnlFeatures;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlOfertas;
    private javax.swing.JPanel pnlTaller;
    // End of variables declaration//GEN-END:variables
}
