package com.portafolio.motors.ing.sis.proyecto.vista;

import com.portafolio.motors.ing.sis.proyecto.controlador.concesionarioBuilder;
import com.portafolio.motors.ing.sis.proyecto.modelo.SQLstatement;

/**
 *
 * @author Michael González
 */
public class modifyClient extends javax.swing.JPanel {

    private main main;
    private concesionarioBuilder cb;
    SQLstatement instance;
    
    /**
     * Creates new form modifyClient
     * @param main
     */
    public modifyClient(main main) {
        this.instance = new SQLstatement();
        this.main = main;
        initComponents();
    }
    
    private void modifyClient() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
