package com.portafolio.motors.ing.sis.proyecto.vista;

import com.portafolio.motors.ing.sis.proyecto.controlador.Listas;
import com.portafolio.motors.ing.sis.proyecto.controlador.concesionarioBuilder;
import com.portafolio.motors.ing.sis.proyecto.modelo.SQLstatement;
import java.awt.Color;
import static javafx.scene.paint.Color.color;
import javax.swing.JOptionPane;

/**
 *
 * @author Yonier Asprilla
 */
public class modifyConcessionaire extends javax.swing.JPanel {
    
    private main main;
    private concesionarioBuilder cb;
    SQLstatement mensajero;
    
    public modifyConcessionaire(main main, concesionarioBuilder cb) {
        this.mensajero = new SQLstatement();
        this.main = main;
        this.cb = cb;
        initComponents();
    }
    
    private void showData() {
        //MANDO DATOS PARA LA BUSQUEDA
        int dato = Integer.parseInt(txtSearch.getText());
        Listas<concesionarioBuilder> datos = mensajero.consultarConcesionarios(dato);
        //SE VALIDA QUE NO SEA NULO
        if (datos != null) {
            try {
                //CARGO LOS DATOS DE LA LISTA
                for (int i = 0; i < datos.size(); i++) {
                    /**
                     * POR MEDIO DEL METODO get() QUE SE ENCUENTRA PROGRAMADO EN
                     * LA LISTA ACCEDO UNO POR UNO A LOS DATOS Y LOS CARGO A LAS
                     * CAJAGAS DE TEXTO EN LA VISTA
                     */
                    txtId.setText(String.valueOf(datos.get(i).getId()));
                    txtNombre.setText(datos.get(i).getNombre());
                    txtDireccion.setText(datos.get(i).getDireccion());
                    txtTelefono.setText(String.valueOf(datos.get(i).getTelefono()));
                }
                
            } catch (Exception e) {
            }
        }
    }
    
    private void modificarDatos() {
        try {
            /**
             * PARA ESTE STEP HAY QUE PRIMERO OBTENER LOS DATOS QUE
             * ANTERIORMENTE PLASMAMOS EN LOS TXT Y ALMACENAR ESOS DATOS EN LAS
             * VARIABLES ALLÍ ESPECIFICADAS, EL SEGUNDO STEP SERIA QUE UNA VEZ
             * QUE LOS DATOS SE SE HALLAN MODIFICADO RESPECTIVAMENTE HAY QUE
             * MANDARLOS A LA BD PARA SU ACTUALIZACIÓN.
             */
            int id = Integer.parseInt(txtId.getText());
            String nombre = txtNombre.getText();
            String direccion = txtDireccion.getText();
            int telefono = Integer.parseInt(txtTelefono.getText());
            
            int confirm = JOptionPane.showConfirmDialog(null, "¿Estas seguro de modificar tus datos?", "Motors", JOptionPane.INFORMATION_MESSAGE);
            if (confirm == 0) {
                boolean modificar = mensajero.modificarConcesionarios(id, nombre, direccion, telefono);
                System.out.println("LA VISTA TIENE ID " + id);
                System.out.println("LA VISTA TIENE NOMBRE " + nombre);
                System.out.println("LA VISTA TIENE DIRECCION " + direccion);
                System.out.println("LA VISTA TIENE TELEFONO " + telefono);
                if (modificar != false) {
                    new alertas.AlertInformation(main, true).setVisible(true);
                    //JOptionPane.showMessageDialog(null, "¡Datos modificados con exito!", "Motors", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
        } catch (NumberFormatException e) {
            System.out.println("LA VISTA DIJO: " + e.getMessage());
        }
        
    }
    
    private void roadTripStepOne() {
        
        if (!txtId.equals("") || txtNombre.equals("") || txtDireccion.equals("") || txtTelefono.equals("")) {
            step1.setBackground(new Color(0, 19, 56));
            line.setForeground(new Color(0, 19, 56));
            line.setBackground(new Color(0, 19, 56));
        }
        
    }
    
    private void roadTripStepTwo() {
        if (!txtId.equals("") || txtNombre.equals("") || txtDireccion.equals("") || txtTelefono.equals("")) {
            step2.setBackground(new Color(0, 19, 56));
//        line.setForeground(new Color(0, 19, 56));
//        line.setBackground(new Color(0, 19, 56));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new LIB.FSTexFieldMD();
        btnBuscar = new keeptoo.KButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        step2 = new LIB.FSLabel();
        line = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        step1 = new LIB.FSLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnAtras = new keeptoo.KButton();
        btnAceptar = new keeptoo.KButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 237, 35));

        jPanel2.setBackground(new java.awt.Color(14, 14, 14));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("CONCESIONARIOS");

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Motors &");

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Asociados");

        txtSearch.setBackground(new java.awt.Color(29, 35, 58));
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setBordeColorNoFocus(new java.awt.Color(51, 51, 51));
        txtSearch.setColorTransparente(true);
        txtSearch.setMaterialDesing(true);
        txtSearch.setPlaceholder("Buscar Por ID");
        txtSearch.setSelectionColor(new java.awt.Color(0, 0, 0));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorderPainted(false);
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setIconTextGap(8);
        btnBuscar.setkBackGroundColor(new java.awt.Color(38, 39, 41));
        btnBuscar.setkEndColor(new java.awt.Color(0, 193, 56));
        btnBuscar.setkHoverColor(new java.awt.Color(24, 25, 63));
        btnBuscar.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnBuscar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnBuscar.setkHoverStartColor(new java.awt.Color(14, 14, 14));
        btnBuscar.setkPressedColor(new java.awt.Color(24, 25, 63));
        btnBuscar.setkStartColor(new java.awt.Color(51, 102, 0));
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnBuscar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnBuscar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/img/miniLogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 542));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Estas a punto");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("DATOS IMPORTANTES");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("DE MODIFICAR");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        step2.setBackground(new java.awt.Color(204, 204, 204));
        step2.setForeground(new java.awt.Color(255, 255, 255));
        step2.setText("2");
        step2.setLineColor(new java.awt.Color(153, 153, 153));
        add(step2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 40, 40));

        line.setBackground(new java.awt.Color(153, 153, 153));
        line.setForeground(new java.awt.Color(204, 204, 204));
        line.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 10, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/img/miniLogo.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1003, 0, 40, 40));

        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("ID");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, -1, -1));

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Nombre");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, -1, -1));

        step1.setBackground(new java.awt.Color(204, 204, 204));
        step1.setForeground(new java.awt.Color(255, 255, 255));
        step1.setText("1");
        step1.setLineColor(new java.awt.Color(153, 153, 153));
        add(step1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 40, 40));

        txtNombre.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 237, 35));

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Direccion");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, -1, -1));

        txtDireccion.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 237, 35));

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Telefono");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 237, 35));

        btnAtras.setText("Atras");
        btnAtras.setBorderPainted(false);
        btnAtras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras.setIconTextGap(8);
        btnAtras.setkBackGroundColor(new java.awt.Color(136, 136, 136));
        btnAtras.setkEndColor(new java.awt.Color(136, 136, 136));
        btnAtras.setkHoverColor(new java.awt.Color(24, 25, 63));
        btnAtras.setkHoverEndColor(new java.awt.Color(136, 136, 136));
        btnAtras.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAtras.setkHoverStartColor(new java.awt.Color(14, 14, 14));
        btnAtras.setkPressedColor(new java.awt.Color(136, 136, 136));
        btnAtras.setkSelectedColor(new java.awt.Color(136, 136, 136));
        btnAtras.setkStartColor(new java.awt.Color(136, 136, 136));
        btnAtras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAtras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAtras.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 60, 30));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorderPainted(false);
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptar.setIconTextGap(8);
        btnAceptar.setkBackGroundColor(new java.awt.Color(38, 39, 41));
        btnAceptar.setkEndColor(new java.awt.Color(0, 193, 56));
        btnAceptar.setkHoverColor(new java.awt.Color(24, 25, 63));
        btnAceptar.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnAceptar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAceptar.setkHoverStartColor(new java.awt.Color(14, 14, 14));
        btnAceptar.setkPressedColor(new java.awt.Color(24, 25, 63));
        btnAceptar.setkStartColor(new java.awt.Color(51, 102, 0));
        btnAceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 138, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        showData();
        roadTripStepOne();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        main.irDashboard(this, cb);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        modificarDatos();
        roadTripStepTwo();
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnAceptar;
    private keeptoo.KButton btnAtras;
    private keeptoo.KButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator line;
    private LIB.FSLabel step1;
    private LIB.FSLabel step2;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private LIB.FSTexFieldMD txtSearch;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
