package com.portafolio.motors.ing.sis.proyecto.vista;

import com.portafolio.motors.ing.sis.proyecto.controlador.Listas;
import com.portafolio.motors.ing.sis.proyecto.controlador.concesionarioBuilder;
import com.portafolio.motors.ing.sis.proyecto.controlador.employeeBuilder;
import com.portafolio.motors.ing.sis.proyecto.modelo.SQLstatement;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Yonier Asprilla
 */
public class modifyEmployee extends javax.swing.JPanel {

    private concesionarioBuilder cb;
    SQLstatement mensajero = new SQLstatement();

    public modifyEmployee(main main) {
        this.main = main;
        initComponents();
    }
    private main main;

    private void showData() {
        Object busqueda = txtSearch.getText();
        Listas<employeeBuilder> datos = mensajero.buscarPorSeleccion(busqueda);
        if (datos != null) {
            try {
                for (int i = 0; i < datos.size(); i++) {
                    txtId.setText(datos.get(i).getId());
                    txtNombre.setText(datos.get(i).getNombre());
                    txtApellidos.setText(datos.get(i).getApellidos());
                    txtDireccion.setText((String) datos.get(i).getDireccion());
                    txtTelefono.setText(datos.get(i).getTelefono());
                    txtDNI.setText(datos.get(i).getDni());
                    txtSalario.setText((String) datos.get(i).getSueldo());
                    txtJefe.setText(datos.get(i).getJefe());
                    txtDateIn.setText(String.valueOf(datos.get(i).getFechaAlta()));
                    txtDateOut.setText(String.valueOf(datos.get(i).getFechaBaja()));
                    txtCargo.setText(datos.get(i).getTipoEmpleado());

                }
            } catch (Exception e) {
                System.out.println("LA VISTA DIJO: " + e.getMessage());
            }
        }
    }

    private void modifyEmployee() {

        String id = txtId.getText();
        String nombre = txtNombre.getText();
        String apellidos = txtApellidos.getText();
        Object direccion = txtDireccion.getText();
        String telefono = txtTelefono.getText();
        String dni = txtDNI.getText();
        Object sueldo = txtSalario.getText();
        String encargado = txtJefe.getText();
        Date entrada = Date.valueOf(txtDateIn.getText());
        Date salida = Date.valueOf(txtDateOut.getText());
        String cargo = txtCargo.getText();

        int confirm = JOptionPane.showConfirmDialog(null, "¿Estas seguro de modificar tus datos?", "Motors", JOptionPane.INFORMATION_MESSAGE);
        if (confirm == 0) {
            boolean modify = mensajero.modifyEmployee(id, nombre, apellidos, direccion, telefono, dni, sueldo, encargado, entrada, salida, cargo);
            if (modify != false) {
                new alertas.AlertInformation(main, true).setVisible(true);
                JOptionPane.showMessageDialog(null, "¡Se han modificado los datos con exito!", "Motors", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSearch = new LIB.FSTexFieldMD();
        btnBuscar = new keeptoo.KButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        step1 = new LIB.FSLabel();
        line = new javax.swing.JSeparator();
        step2 = new LIB.FSLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDateIn = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        undefined = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnAceptar = new keeptoo.KButton();
        txtDateOut = new javax.swing.JTextField();
        txtJefe = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(14, 14, 14));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("CONCESIONARIOS");

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Motors &");

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Asociados");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/img/miniLogo.png"))); // NOI18N

        txtSearch.setBackground(new java.awt.Color(29, 35, 58));
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setBordeColorNoFocus(new java.awt.Color(51, 51, 51));
        txtSearch.setColorTransparente(true);
        txtSearch.setMaterialDesing(true);
        txtSearch.setPlaceholder("Buscar Por Nombre");
        txtSearch.setSelectionColor(new java.awt.Color(0, 0, 0));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorderPainted(false);
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setIconTextGap(8);
        btnBuscar.setkBackGroundColor(new java.awt.Color(38, 39, 41));
        btnBuscar.setkEndColor(new java.awt.Color(0, 193, 56));
        btnBuscar.setkHoverColor(new java.awt.Color(24, 25, 63));
        btnBuscar.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnBuscar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnBuscar.setkHoverStartColor(new java.awt.Color(14, 14, 14));
        btnBuscar.setkPressedColor(new java.awt.Color(24, 25, 63));
        btnBuscar.setkStartColor(new java.awt.Color(51, 102, 0));
        btnBuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnBuscar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnBuscar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 610));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Estas a punto");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("DE MODIFICAR");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("DATOS IMPORTANTES");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        step1.setBackground(new java.awt.Color(204, 204, 204));
        step1.setForeground(new java.awt.Color(255, 255, 255));
        step1.setText("1");
        step1.setLineColor(new java.awt.Color(153, 153, 153));
        add(step1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 40, 40));

        line.setBackground(new java.awt.Color(153, 153, 153));
        line.setForeground(new java.awt.Color(204, 204, 204));
        line.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(line, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 10, 100));

        step2.setBackground(new java.awt.Color(204, 204, 204));
        step2.setForeground(new java.awt.Color(255, 255, 255));
        step2.setText("2");
        step2.setLineColor(new java.awt.Color(153, 153, 153));
        add(step2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 40, 40));

        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Telefono");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 237, 35));

        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("DNI");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 70, -1, -1));

        txtDNI.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 90, 237, 35));

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Fecha Ingreso");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 210, -1, -1));

        txtDateIn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        add(txtDateIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 230, 237, 35));

        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Usename");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, -1, -1));

        txtId.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 237, 35));

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Nombres");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, -1, -1));

        txtNombre.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 237, 35));

        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Apellidos");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, -1));

        txtApellidos.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 237, 35));

        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Direccion");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, -1, -1));

        txtDireccion.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 237, 35));

        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Jefe Encargado");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 140, -1, -1));

        undefined.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        undefined.setText("Undefined");
        undefined.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undefinedActionPerformed(evt);
            }
        });
        add(undefined, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 310, -1, -1));

        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Fecha Salida");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 360, -1, -1));

        txtSalario.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, 237, 35));

        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Salario");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));

        txtCargo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 450, 237, 35));

        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Cargo");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 430, -1, -1));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorderPainted(false);
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptar.setIconTextGap(8);
        btnAceptar.setkBackGroundColor(new java.awt.Color(38, 39, 41));
        btnAceptar.setkEndColor(new java.awt.Color(0, 193, 56));
        btnAceptar.setkHoverColor(new java.awt.Color(24, 25, 63));
        btnAceptar.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnAceptar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAceptar.setkHoverStartColor(new java.awt.Color(14, 14, 14));
        btnAceptar.setkPressedColor(new java.awt.Color(24, 25, 63));
        btnAceptar.setkStartColor(new java.awt.Color(51, 102, 0));
        btnAceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 530, 138, -1));

        txtDateOut.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        add(txtDateOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 380, 237, 35));

        txtJefe.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        add(txtJefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 160, 237, 35));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
//        showData();
//        roadTripStepOne();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void undefinedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undefinedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_undefinedActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
//        modificarDatos();
//        roadTripStepTwo();
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnAceptar;
    private keeptoo.KButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator line;
    private LIB.FSLabel step1;
    private LIB.FSLabel step2;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDateIn;
    private javax.swing.JTextField txtDateOut;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJefe;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSalario;
    private LIB.FSTexFieldMD txtSearch;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JCheckBox undefined;
    // End of variables declaration//GEN-END:variables
}
