package com.portafolio.motors.ing.sis.proyecto.vista;

import com.portafolio.motors.ing.sis.proyecto.controlador.concesionarioBuilder;
import com.portafolio.motors.ing.sis.proyecto.modelo.SQLstatement;
import javax.swing.JOptionPane;
import keeptoo.Drag;

/**
 *
 * @author Michael González
 */
public class newClient extends javax.swing.JPanel {
    
    private main main;
    private concesionarioBuilder cb;
    SQLstatement instance;

    /**
     * Creates new form newClient
     *
     * @param main
     */
    public newClient(main main) {
        this.instance = new SQLstatement();
        this.main = main;
        initComponents();
    }
    
    private void addClient() {
        try {
            int id = Integer.parseInt(txtId.getText());
            String nombre = txtPhone.getText();
            String apellidos = txtLastname.getText();
            String telefono = txtPhone.getText();
            String email = txtEmail.getText();
            java.util.Date fNac = txtBirth.getDate();
            long formato = fNac.getTime();
            java.sql.Date entrada = new java.sql.Date(formato);
            String profesion = txtProfession.getText();

            /* if (id.equals("") || nombre.equals("") || apellidos.equals("") || telefono.equals("")
                    || email.equals("") || profesion.equals("")) {
                
            } else {*/
            boolean add = instance.addClient(id, nombre, apellidos, Integer.parseInt(telefono), email, entrada, profesion);
            if (add != false) {
                new alertas.AlertInformation(main, true).setVisible(true);
                //JOptionPane.showMessageDialog(null, "¡Los datos del cliente se han ingresado correctamente!", "Motors", 1);
                System.out.println("Enviando " + id);
                System.out.println("Enviando " + nombre);
                System.out.println("Enviando " + apellidos);
                System.out.println("Enviando " + telefono);
                System.out.println("Enviando " + email);
                System.out.println("Enviando " + entrada.toString());
                System.out.println("Enviando " + profesion);
            } else {
                // JOptionPane.showMessageDialog(null, "Ocurrió un error a ingresar sus datos. Inténtelo de nuevo", "Motors", 0);
                new alertas.AlertError(main, true).setVisible(true);
            }
            // }
        } catch (NumberFormatException | NullPointerException e) {
            System.out.println("Campos incompletos " + e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos.", "ERROR", 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnAddClient = new keeptoo.KButton();
        txtBirth = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnBack = new keeptoo.KButton();
        txtLastname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtName1 = new javax.swing.JTextField();
        txtProfession = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(960, 520));
        setOpaque(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(14, 14, 14));

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CONCESIONARIOS");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/img/logos.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("MOTORS &");

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/img/miniLogo.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("ASOCIADOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(135, 135, 135)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 608));

        btnAddClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAddClient.setText("         Agregar");
        btnAddClient.setBorderPainted(false);
        btnAddClient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddClient.setIconTextGap(14);
        btnAddClient.setkEndColor(new java.awt.Color(24, 25, 63));
        btnAddClient.setkHoverEndColor(new java.awt.Color(0, 234, 60));
        btnAddClient.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAddClient.setkHoverStartColor(new java.awt.Color(0, 43, 107));
        btnAddClient.setkPressedColor(new java.awt.Color(24, 25, 63));
        btnAddClient.setkStartColor(new java.awt.Color(38, 39, 41));
        btnAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClientActionPerformed(evt);
            }
        });
        add(btnAddClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, 128, 42));

        txtBirth.setBackground(new java.awt.Color(204, 204, 204));
        txtBirth.setForeground(new java.awt.Color(102, 102, 102));
        add(txtBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 237, 35));

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/img/prueba.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, -1, 240));

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Fecha de nacimiento");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, -1, -1));

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Profesión");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, -1));

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Teléfono de contacto");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("E-mail");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, -1, -1));

        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Apellido(s)");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, -1, -1));

        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Identificación");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        btnBack.setText("Atrás");
        btnBack.setBorderPainted(false);
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setkBackGroundColor(new java.awt.Color(136, 136, 136));
        btnBack.setkEndColor(new java.awt.Color(136, 136, 136));
        btnBack.setkHoverColor(new java.awt.Color(24, 25, 63));
        btnBack.setkHoverEndColor(new java.awt.Color(136, 136, 136));
        btnBack.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnBack.setkHoverStartColor(new java.awt.Color(14, 14, 14));
        btnBack.setkPressedColor(new java.awt.Color(136, 136, 136));
        btnBack.setkSelectedColor(new java.awt.Color(136, 136, 136));
        btnBack.setkStartColor(new java.awt.Color(136, 136, 136));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 28, 68, 29));

        txtLastname.setBackground(new java.awt.Color(54, 55, 59));
        txtLastname.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtLastname.setForeground(new java.awt.Color(255, 255, 255));
        txtLastname.setToolTipText("");
        txtLastname.setName(""); // NOI18N
        add(txtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 237, 35));

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("<html>vas AGREGA UN<p>NUEVO CLIENTE a la organizacion");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 270, 130));

        txtPhone.setBackground(new java.awt.Color(54, 55, 59));
        txtPhone.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(255, 255, 255));
        txtPhone.setToolTipText("");
        txtPhone.setName(""); // NOI18N
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 237, 35));

        txtId.setBackground(new java.awt.Color(54, 55, 59));
        txtId.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setToolTipText("");
        txtId.setName(""); // NOI18N
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 237, 35));

        txtEmail.setBackground(new java.awt.Color(54, 55, 59));
        txtEmail.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setToolTipText("");
        txtEmail.setName(""); // NOI18N
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 237, 35));

        txtName1.setBackground(new java.awt.Color(54, 55, 59));
        txtName1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtName1.setForeground(new java.awt.Color(255, 255, 255));
        txtName1.setToolTipText("");
        txtName1.setName(""); // NOI18N
        add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 237, 35));

        txtProfession.setBackground(new java.awt.Color(54, 55, 59));
        txtProfession.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtProfession.setForeground(new java.awt.Color(255, 255, 255));
        txtProfession.setToolTipText("");
        txtProfession.setName(""); // NOI18N
        add(txtProfession, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 237, 35));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 240, 10));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/download.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/print.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 30, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        main.irDashboard(this, cb);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClientActionPerformed
        addClient();
    }//GEN-LAST:event_btnAddClientActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        new Drag(jPanel1).onPress(evt);
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        new Drag(jPanel1).moveWindow(evt);
    }//GEN-LAST:event_formMouseDragged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnAddClient;
    private keeptoo.KButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser txtBirth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtProfession;
    // End of variables declaration//GEN-END:variables
}
