package com.portafolio.motors.ing.sis.proyecto.vista;

import com.placeholder.PlaceHolder;
import com.portafolio.motors.ing.sis.proyecto.modelo.SQLstatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Yonier Asprilla
 */
public class newConcessionaire extends javax.swing.JPanel {

    SQLstatement mensajero = new SQLstatement();
    PlaceHolder holder;
    private main main;

    public newConcessionaire(main main) {
        this.main = main;
        initComponents();
        placeholder();
    }

    private void placeholder() {

        //TextPrompt nombre = new TextPrompt(" Nombres & Apellidos", txtId);
        //holder = new PlaceHolder(txtId, " ID");
        holder = new PlaceHolder(txtNombre, " Nombre");
        holder = new PlaceHolder(txtDireccion, " Direccion");
        holder = new PlaceHolder(txtTelefono, " Telefono");
    }

    private void registrar() {

        int id = Integer.parseInt(txtId.getText());
        String nombre = txtNombre.getText();
        String direccion = txtDireccion.getText();
        int telefono = Integer.parseInt(txtTelefono.getText());
        
        if (txtId.equals("") || txtNombre.equals("") || txtDireccion.equals("") || txtTelefono.equals("")) {
            JOptionPane.showMessageDialog(null, "¡Por favor llena todos los campos!", "Motors", JOptionPane.WARNING_MESSAGE);
        } else {
            boolean agregar = mensajero.nuevosConcesionarios(id, nombre, direccion, telefono);
            if (agregar != false) {
                JOptionPane.showMessageDialog(null, "¡El concesionario se ha agregado al equipo!", "Motors", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "¡No hemos podido agregar el concesionario!", "Motors", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    private void limpiar() {
        txtId.setText(null);
        txtNombre.setText(null);
        txtDireccion.setText(null);
        txtTelefono.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAceptar = new keeptoo.KButton();
        btnAtras = new keeptoo.KButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(38, 39, 41));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(29, 35, 58));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/img/logos.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 80, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Motors");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, 30));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 11, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 227, 520));

        txtId.setBackground(new java.awt.Color(54, 55, 59));
        txtId.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setToolTipText("");
        txtId.setName(""); // NOI18N
        add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 111, 237, 35));

        txtNombre.setBackground(new java.awt.Color(54, 55, 59));
        txtNombre.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 164, 237, 35));

        txtDireccion.setBackground(new java.awt.Color(54, 55, 59));
        txtDireccion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 217, 237, 35));

        txtTelefono.setBackground(new java.awt.Color(54, 55, 59));
        txtTelefono.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 270, 237, 35));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Wellcome");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 111, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vas a asociar un");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 144, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Concesionario");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 166, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 21)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Al equipo");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 191, -1, 50));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorderPainted(false);
        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAceptar.setIconTextGap(12);
        btnAceptar.setkBackGroundColor(new java.awt.Color(24, 25, 63));
        btnAceptar.setkEndColor(new java.awt.Color(24, 25, 63));
        btnAceptar.setkHoverColor(new java.awt.Color(24, 25, 63));
        btnAceptar.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnAceptar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAceptar.setkHoverStartColor(new java.awt.Color(24, 25, 63));
        btnAceptar.setkPressedColor(new java.awt.Color(24, 25, 63));
        btnAceptar.setkStartColor(new java.awt.Color(38, 39, 41));
        btnAceptar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 334, 138, -1));

        btnAtras.setText("Atras");
        btnAtras.setBorderPainted(false);
        btnAtras.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAtras.setkBackGroundColor(new java.awt.Color(55, 56, 59));
        btnAtras.setkEndColor(new java.awt.Color(55, 56, 59));
        btnAtras.setkStartColor(new java.awt.Color(55, 56, 59));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 33, 64, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/img/miniLogo.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 40, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 240, 10));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/descargar.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/imprimir.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        registrar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
       main.irDashboard(this);
    }//GEN-LAST:event_btnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnAceptar;
    private keeptoo.KButton btnAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
