package com.portafolio.motors.ing.sis.proyecto.vista;

import com.portafolio.motors.ing.sis.proyecto.controlador.Listas;
import com.portafolio.motors.ing.sis.proyecto.controlador.concesionarioBuilder;
import com.portafolio.motors.ing.sis.proyecto.modelo.SQLstatement;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Yonier Asprilla
 */
public class showConcessionaire extends javax.swing.JPanel {

    private main main;
    private concesionarioBuilder cb;
    DefaultTableModel model = new DefaultTableModel();
    TableRowSorter trs;
    SQLstatement mensajero = new SQLstatement();

    public showConcessionaire(main main, concesionarioBuilder cb) {
        this.main = main;
        this.cb = cb;
        initComponents();
        mostrarConcesionarios();
    }

    /**
     * ESTE METODO SIMPLEMENTE LO UTILIZAREMOS PARA CARGAR LOS DATOS Y
     * MOSTRARLOS EN LA TABLA RESPECTIVAMENTE
     *
     */
    private void mostrarConcesionarios() {

        this.model.addColumn("ID");
        this.model.addColumn("Nombre");
        this.model.addColumn("Direccion");
        this.model.addColumn("Telefono");
        tbConcesionarios.setModel(model);

        Listas<concesionarioBuilder> datos = mensajero.buscarConcesionarios();
        if (datos != null) {
            Object[] filas = new Object[4];
            try {
                for (int i = 0; i < datos.size(); i++) {
                    filas[0] = (datos.get(i).getId());
                    filas[1] = (datos.get(i).getNombre());
                    filas[2] = (datos.get(i).getDireccion());
                    filas[3] = (datos.get(i).getTelefono());
                    model.addRow(filas);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "¡No se pudieron cargar los datos", "Motors", JOptionPane.ERROR_MESSAGE);
            }

        }

    }

    /**
     * ESTE METODO LO UTILIZAREMOS PARA PODER ELIMINAR LOS CONCESIONARIOS QUE SE
     * DESEEN POR MEDIO DE UNA BUSQUEDA POR ID, PRIMERO SE CARGARAN LOS DATOS
     * DESDE EL MODELO Y LUEGO LO ELIMINAREMOS DESDE EL CONTROLADOR CON LA LISTA
     */
    private void eliminarConcesionario() {

        try {

            int dato = Integer.parseInt(txtSearch.getText());
            Listas<concesionarioBuilder> borrar = mensajero.eliminarConcesionarios(dato);
            if (borrar != null && !txtSearch.getText().equals("")) {
                for (int i = 0; i < borrar.size(); i--) {
                    borrar.remove(i).getId();
                    borrar.remove(i).getNombre();
                    borrar.remove(i).getDireccion();
                    borrar.remove(i).getTelefono();
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error al cargar los datos", "Motors", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void filtro() {
        txtSearch.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)" + txtSearch.getText(), 0));
            }
        });
        trs = new TableRowSorter(model);
        tbConcesionarios.setRowSorter(trs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbConcesionarios = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new LIB.FSTexFieldMD();
        btnDesvincular = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbConcesionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbConcesionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbConcesionarios.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tbConcesionarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 1010, 510));

        jPanel1.setBackground(new java.awt.Color(14, 14, 14));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearch.setBackground(new java.awt.Color(29, 35, 58));
        txtSearch.setForeground(new java.awt.Color(255, 255, 255));
        txtSearch.setBordeColorNoFocus(new java.awt.Color(153, 153, 255));
        txtSearch.setColorTransparente(true);
        txtSearch.setMaterialDesing(true);
        txtSearch.setPlaceholder("Filtrar por id");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 150, -1));

        btnDesvincular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/trash.png"))); // NOI18N
        btnDesvincular.setText("Desvincular");
        btnDesvincular.setBorderPainted(false);
        btnDesvincular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDesvincular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDesvincular.setIconTextGap(8);
        btnDesvincular.setkBackGroundColor(new java.awt.Color(38, 39, 41));
        btnDesvincular.setkEndColor(new java.awt.Color(0, 193, 56));
        btnDesvincular.setkHoverColor(new java.awt.Color(24, 25, 63));
        btnDesvincular.setkHoverEndColor(new java.awt.Color(0, 193, 56));
        btnDesvincular.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDesvincular.setkHoverStartColor(new java.awt.Color(24, 25, 63));
        btnDesvincular.setkPressedColor(new java.awt.Color(24, 25, 63));
        btnDesvincular.setkStartColor(new java.awt.Color(51, 102, 0));
        btnDesvincular.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnDesvincular.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnDesvincular.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnDesvincular.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/usVerified.png"))); // NOI18N
        btnDesvincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesvincularActionPerformed(evt);
            }
        });
        jPanel1.add(btnDesvincular, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 138, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/icon/back.png"))); // NOI18N
        jLabel1.setText("Atras");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 40));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("CONCESIONARIOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Motors &");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Asociados");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/portafolio/motors/ing/sis/proyecto/img/miniLogo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 96, -1, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        filtro();
    }//GEN-LAST:event_txtSearchKeyTyped

    private void btnDesvincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesvincularActionPerformed
        eliminarConcesionario();
    }//GEN-LAST:event_btnDesvincularActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        main.irDashboard(this, cb);
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnDesvincular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbConcesionarios;
    private LIB.FSTexFieldMD txtSearch;
    // End of variables declaration//GEN-END:variables
}
