-- ////////////////////////////////////////////////////////////////////////////////////////////////////
-- CLIENTES PROCEDURES
-- ////////////////////////////////////////////////////////////////////////////////////////////////////

-- AGREGAR CLIENTE 
DELIMITER $$
CREATE PROCEDURE SP_AGREGARCLIENTE (
  CLI_ID_ INT(10),
  CLI_NOMBRE_ VARCHAR(80),
  CLI_APELLIDOS_ VARCHAR(80),
  CLI_TELEFONO_ INT(15),
  CLI_EMAIL_ VARCHAR(45),
  CLI_FNAC_ DATE,
  CLI_PROFESION_ VARCHAR(45)
)
BEGIN
	INSERT INTO concesionario.GC_CLIENTE(CLI_ID,CLI_NOMBRE,CLI_APELLIDOS,CLI_TELEFONO,CLI_EMAIL,CLI_FNAC,CLI_PROFESION)
										 VALUES(CLI_ID_,CLI_NOMBRE_,CLI_APELLIDOS_,CLI_TELEFONO_,CLI_EMAIL_,CLI_FNAC_,CLI_PROFESION_);
END
DELIMITER $$

-- BORRAR CLIENTE
DELIMITER $$
CREATE PROCEDURE SP_ELIMINARCLIENTE (
	CLI_ID_ INT(10)
)
BEGIN
DELETE FROM concesionarios.GC_CLIENTE WHERE CLI_ID = CLI_ID_;
END
DELIMITER $$

-- ACTUALIZAR CLIENTE
DELIMITER $$
CREATE PROCEDURE SP_MODIFICARCLIENTE (
  CLI_ID_ INT(10),
  CLI_NOMBRE_ VARCHAR(80),
  CLI_APELLIDOS_ VARCHAR(80),
  CLI_TELEFONO_ INT(15),
  CLI_EMAIL_ VARCHAR(45),
  CLI_FNAC_ DATE,
  CLI_PROFESION_ VARCHAR(45)
)
BEGIN
UPDATE concesionarios.GC_CLIENTE SET CLI_ID = CLI_ID_, CLI_NOMBRE = CLI_NOMBRE_, CLI_APELLIDOS = CLI_APELLIDOS_, CLI_TELEFONO = CLI_TELEFONO_, CLI_EMAIL = CLI_EMAIL_, CLI_FNAC = CLI_FNAC_, CLI_PROFESION = CLI_PROFESION_ 
								 WHERE CLI_ID = CLI_ID_;
END
DELIMITER $$

-- ////////////////////////////////////////////////////////////////////////////////////////////////////
-- TAREAS PROCEDURES
-- ////////////////////////////////////////////////////////////////////////////////////////////////////

-- AGREGAR TAREAS
DELIMITER $$
CREATE PROCEDURE SP_AGREGARTAREA (
  TAR_ID_ INT(10),
  TAR_CONCEPTO_ VARCHAR(200),
  TAR_HORAS_ INT(10),
  TAR_FACTURABLE_ VARCHAR(45),
  TAR_ESTADO_ BOOLEAN
)
BEGIN
INSERT INTO concesionarios.GC_TAREA(TAR_ID,TAR_CONCEPTO,TAR_HORAS,TAR_FACTURABLE,TAR_ESTADO)
									VALUES(TAR_ID_,TAR_CONCEPTO_,TAR_HORAS_,TAR_FACTURABLE_,TAR_ESTADO_);
END
DELIMITER $$

-- BORRAR TAREA
DELIMITER $$
CREATE PROCEDURE SP_ELIMINARTAREA (
	TAR_ID_ INT(10)
)
BEGIN
DELETE FROM concesionarios.GC_TAREA WHERE TAR_ID = TAR_ID_;
END
DELIMITER $$

-- ACTUALIZAR TAREAS
DELIMITER $$
CREATE PROCEDURE SP_MODIFICARTAREA (
  TAR_ID_ INT(10),
  TAR_CONCEPTO_ VARCHAR(200),
  TAR_HORAS_ INT(10),
  TAR_FACTURABLE_ VARCHAR(45),
  TAR_ESTADO_ BOOLEAN
)
BEGIN
	UPDATE concesionarios.GC_TAREA SET TAR_ID = TAR_ID_, TAR_CONCEPTO = TAR_CONCEPTO_, TAR_HORAS = TAR_HORAS_, TAR_FACTURABLE = TAR_FACTURABLE_, TAR_ESTADO = TAR_ESTADO_ WHERE TAR_ID = TAR_ID_;
END
DELIMITER $$

-- ACTUALIZAR EL ESTADO DE LA TAREA
DELIMITER $$
CREATE PROCEDURE SP_MODIFICARESTADOTAREA (
	TAR_ESTADO_ BOOLEAN
)
BEGIN
	UPDATE concesionarios.GC_TAREA SET TAR_ESTADO = TAR_ESTADO_ WHERE TAR_ID = TAR_ID_;
END
DELIMITER $$

-- ////////////////////////////////////////////////////////////////////////////////////////////////////
-- USUARIOS PROCEDURES
-- ////////////////////////////////////////////////////////////////////////////////////////////////////

-- AGREGAR USUARIOS
DELIMITER $$
CREATE PROCEDURE SP_AGREGARUSUARIO (
 USR_ID_ VARCHAR(80),
 USR_PASS_ VARCHAR(45),
 USR_PERMISOS_ VARCHAR(3)
)
BEGIN
	INSERT INTO concesionarios.GC_USUARIO(USR_ID,USR_PASS,USR_PERMISOS) VALUES (USR_ID_,USR_PASS_,USR_PERMISOS_);
END
DELIMITER $$

-- BORRAR USUARIOS
DELIMITER $$
CREATE PROCEDURE SP_ELIMINARUSUARIO (
	USR_ID_ VARCHAR(80)
)
BEGIN
	DELETE FROM concesionarios.GC_USUARIO WHERE USR_ID = USR_ID_;
END
DELIMITER $$

-- ACTUALIZAR USUARIO
DELIMITER $$
CREATE PROCEDURE SP_MODIFICARUSUARIO (
	USR_ID_ VARCHAR(80),
	USR_PASS_ VARCHAR(45),
	USR_PERMISOS_ VARCHAR(3)
)
BEGIN
	UPDATE concesionarios.GC_USUARIO SET USR_ID = USR_ID_, USR_PASS = USR_PASS_, USR_PERMISOS = USR_PERMISOS_ WHERE USR_ID = USR_ID_;
END
DELIMITER $$

-- ////////////////////////////////////////////////////////////////////////////////////////////////////
-- VEHICULO PROCEDURES
-- ////////////////////////////////////////////////////////////////////////////////////////////////////

-- AGREGAR VEHICULO
DELIMITER $$
CREATE PROCEDURE SP_AGREGARVEHICULO (
	VEH_ID_ INT(10),
	VEH_BASTIDOR_ VARCHAR(80),
    VEH_MATRICULA_ VARCHAR(15),
    VEH_COLOR_ VARCHAR(45),
    VEH_VENDIDO_ VARCHAR(30)
)
BEGIN
	INSERT INTO concesionarios.GC_VEHICULO(VEH_ID,VEH_BASTIDOR,VEH_MATRICULA,VEH_COLOR,VEH_VENDIDO)
										   VALUES (VEH_ID_,VEH_BASTIDOR_,VEH_MATRICULA_,VEH_COLOR_,VEH_VENDIDO_);
END
DELIMITER $$

-- BORRAR VEHICULO
DELIMITER $$
CREATE PROCEDURE SP_ELIMINARVEHICULO (
	VEH_ID_ INT(10)
)
BEGIN
	DELETE FROM concesionarios.GC_VEHICULO WHERE VEH_ID = VEH_ID_;
END 
DELIMITER $$

-- ACTUALIZAR VEHICULO
DELIMITER $$
CREATE PROCEDURE SP_MODIFICARVEHICULO (
	VEH_ID_ INT(10),
	VEH_BASTIDOR_ VARCHAR(80),
    VEH_MATRICULA_ VARCHAR(15),
    VEH_COLOR_ VARCHAR(45),
    VEH_VENDIDO_ VARCHAR(30)
)
BEGIN
	UPDATE concesionarios.GC_VEHICULO SET VEH_ID = VEH_ID_, VEH_BASTIDOR = VEH_BASTIDOR_, VEH_MATRICULA = VEH_MATRICULA_, VEH_COLOR = VEH_COLOR_, VEH_VENDIDO = VEH_VENDIDO_ WHERE VEH_ID = VEH_ID_;
END
DELIMITER $$

-- ////////////////////////////////////////////////////////////////////////////////////////////////////
-- VENTA PROCEDURES
-- ////////////////////////////////////////////////////////////////////////////////////////////////////

-- AGREGAR VENTAS
DELIMITER $$
CREATE PROCEDURE SP_AGREGARVENTAS (
	VEN_ID_ INT(10),
	VEN_NOMBRE_PRODUCTO_ VARCHAR(80),
    VEN_MODELO_PRODUCTO_ VARCHAR(45),
    VEN_FECHA_ DATE,
    VEN_GARANTIA_ VARCHAR(20),
    VEN_DESCUENTOS_ DOUBLE,
    VEN_VALOR_VENTA_ DOUBLE
)
BEGIN
	INSERT INTO concesionarios.GC_VENTA(VEN_ID,VEN_NOMBRE_PRODUCTO,VEN_MODELO_PRODUCTO,VEN_FECHA,VEN_GARANTIA,VEN_DESCUENTOS,VEN_VALOR_VENTA)
										VALUES(VEN_ID_,VEN_NOMBRE_PRODUCTO_,VEN_MODELO_PRODUCTO_,VEN_FECHA_,VEN_GARANTIA_,VEN_DESCUENTOS_,VEN_VALOR_VENTA_);
END
DELIMITER $$

-- MODIFICAR VENTAS
DELIMITER $$
CREATE PROCEDURE SP_MODIFICARVENTAS (
	VEN_ID_ INT(10),
	VEN_NOMBRE_PRODUCTO_ VARCHAR(80),
    VEN_MODELO_PRODUCTO_ VARCHAR(45),
    VEN_FECHA_ DATE,
    VEN_GARANTIA_ VARCHAR(20),
    VEN_DESCUENTOS_ DOUBLE,
    VEN_VALOR_VENTA_ DOUBLE
)
BEGIN
	UPDATE concesionarios.GC_VENTA SET VEN_ID = VEN_ID_, VEN_NOMBRE_PRODUCTO = VEN_NOMBRE_PRODUCTO_, VEN_MODELO_PRODUCTO = VEN_MODELO_PRODUCTO_, VEN_FECHA = VEN_FECHA_, VEN_GARANTIA = VEN_GARANTIA_, VEN_DESCUENTOS = VEN_DESCUENTOS_, VEN_VALOR_VENTA = VEN_VALOR_VENTA_ 
								   WHERE VEN_ID = VEN_ID_;
END
DELIMITER $$

-- ////////////////////////////////////////////////////////////////////////////////////////////////////
-- CATALOGO PROCEDURES
-- ////////////////////////////////////////////////////////////////////////////////////////////////////

-- AGREGAR ITEM
DELIMITER $$
CREATE PROCEDURE SP_AGREGARITEM (
  CAT_ID_ INT(10),
  CAT_CARID_ INT(10),
  CAT_MODID_ INT(10),
  CAT_EXTRA_ VARCHAR(200),
  CAT_PVP_ DECIMAL(20,3)
)
BEGIN
INSERT INTO concesionarios.GC_CATALOGO (CAT_ID, CAT_CARID, CAT_MODID, CAT_EXTRA, CAT_PVP) VALUES (CAT_ID_, CAT_CARID_, CAT_MODID_, CAT_EXTRA_, CAT_PVP_);
END
DELIMITER $$
-- BORRAR ITEM
DELIMITER $$
CREATE PROCEDURE SP_ELIMINARITEM (
  CAT_ID_ INT(10)
)
BEGIN
DELETE FROM concesionarios.GC_CATALOGO WHERE CAT_ID = CAT_ID_;
END
DELIMITER $$
-- ACTUALIZAR ITEM
DELIMITER $$
CREATE PROCEDURE SP_MODIFICARITEM (
  CAT_ID_ INT(10),
  CAT_CARID_ INT(10),
  CAT_MODID_ INT(10),
  CAT_EXTRA_ VARCHAR(200),
  CAT_PVP_ DECIMAL(20,3)
)
BEGIN
UPDATE concesionarios.GC_CATALOGO SET CAT_ID = CAT_ID_, CAT_CARID = CAT_CARID_, CAT_MODID = CAT_MODID_, CAT_EXTRA = CAT_EXTRA_, CAT_PVP = CAT_PVP_ WHERE CAT_ID = CAT_ID_;
END
DELIMITER $$

-- ////////////////////////////////////////////////////////////////////////////////////////////////////
-- CONFIGURACION PROCEDURES
-- ////////////////////////////////////////////////////////////////////////////////////////////////////

-- AGREGAR CONFIGURACION
DELIMITER $$
CREATE PROCEDURE SP_AGREGARCONFIGURACION (
  CONF_VEHID_ INT(10),
  CONF_CARID_ INT(10),
  CONF_MOTOR_ VARCHAR(35),
  CONF_LLANTAS_ VARCHAR(20),
  CONF_ESPEJOS_ VARCHAR(20),
  CONF_CHASIS_ VARCHAR(35),
  CONF_CILINDRAJE_ VARCHAR(50),
  CONF_RINES_ VARCHAR(30),
  CONF_INTERIOR_ VARCHAR(10)
)
BEGIN
INSERT INTO concesionarios.GC_CONFIGURACION (CONF_VEHID, CONF_CARID, CONF_MOTOR, CONF_LLANTAS, CONF_ESPEJOS, CONF_CHASIS, CONF_CILINDRAJE, CONF_RINES, CONF_INTERIOR) VALUES (CONF_VEHID_, CONF_CARID_, CONF_MOTOR_, CONF_LLANTAS_, CONF_ESPEJOS_, CONF_CHASIS_, CONF_CILINDRAJE_, CONF_RINES_, CONF_INTERIOR_);
END
DELIMITER $$
-- BORRAR CONFIGURACION
DELIMITER $$
CREATE PROCEDURE SP_ELIMINARCONFIGURACION (
  CONF_VEHID_ INT(10)
)
BEGIN
DELETE FROM concesionarios.GC_CONFIGURACION WHERE CONF_VEHID = CONF_VEHID_;
END
DELIMITER $$
-- ACTUALIZAR CONFIGURACION
DELIMITER $$
CREATE PROCEDURE SP_MODIFICARCONFIGURACION (
  CONF_VEHID_ INT(10),
  CONF_CARID_ INT(10),
  CONF_MOTOR_ VARCHAR(35),
  CONF_LLANTAS_ VARCHAR(20),
  CONF_ESPEJOS_ VARCHAR(20),
  CONF_CHASIS_ VARCHAR(35),
  CONF_CILINDRAJE_ VARCHAR(50),
  CONF_RINES_ VARCHAR(30),
  CONF_INTERIOR_ VARCHAR(10)
)
BEGIN
UPDATE concesionarios.GC_CONFIGURACION SET CONF_VEHID = CONF_VEHID_, CONF_CARID = CONF_CARID_, CONF_MOTOR = CONF_MOTOR_, CONF_LLANTAS = CONF_LLANTAS_, CONF_ESPEJOS = CONF_ESPEJOS_, CONF_CHASIS = CONF_CHASIS_, CONF_CILINDRAJE = CONF_CILINDRAJE_, CONF_RINES = CONF_RINES_, CONF_INTERIOR = CONF_INTERIOR_ WHERE CONF_VEHID = CONF_VEHID_;
END
DELIMITER $$

-- ////////////////////////////////////////////////////////////////////////////////////////////////////
-- DESCUENTOS PROCEDURES
-- ////////////////////////////////////////////////////////////////////////////////////////////////////

-- AGREGAR DESCUENTO
DELIMITER $$
CREATE PROCEDURE SP_AGREGARDESCUENTO (
  DES_ID_ INT(10),
  DES_VALOR_ DOUBLE,
  DES_NOMBRE_ VARCHAR(100),
  DES_FACTURAID_ INT(10)
)
BEGIN
INSERT INTO concesionarios.GC_DESCUENTOS (DES_ID, DES_VALOR, DES_NOMBRE, DES_FACTURAID) VALUES (DES_ID_, DES_VALOR_, DES_NOMBRE_, DES_FACTURAID_);
END
DELIMITER $$
--BORRAR DESCUENTO
DELIMITER $$
CREATE PROCEDURE SP_ELIMINARDESCUENTO (
  DES_ID_ INT(10)
)
BEGIN
DELETE FROM concesionarios.GC_DESCUENTOS WHERE DES_ID = DES_ID_;
END
DELIMITER $$
-- ACTUALIZAR DESCUENTO
DELIMITER $$
CREATE PROCEDURE SP_MODIFICAR_DESCUENTO (
  DES_ID_ INT(10),
  DES_VALOR_ DOUBLE,
  DES_NOMBRE_ VARCHAR(100),
  DES_FACTURAID_ INT(10)
)
BEGIN
UPDATE concesionarios.GC_DESCUENTOS SET DES_ID = DES_ID_, DES_VALOR = DES_VALOR_, DES_NOMBRE = DES_NOMBRE_, DES_FACTURAID = DES_FACTURAID_ WHERE DES_ID = DES_ID_;
END
DELIMITER $$

-- ////////////////////////////////////////////////////////////////////////////////////////////////////
-- MARCA PROCEDURES
-- ////////////////////////////////////////////////////////////////////////////////////////////////////

-- AGREGAR MARCA
DELIMITER $$
CREATE PROCEDURE SP_AGREGARMARCA (
  MAR_ID_ INT(10),
  MAR_NOMBRE_ VARCHAR(45)
)
BEGIN
INSERT INTO concesionarios.GC_MARCA (MAR_ID, MAR_NOMBRE) VALUES (MAR_ID_, MAR_NOMBRE_);
END
DELIMITER $$
--BORRAR MARCA
DELIMITER $$
CREATE PROCEDURE SP_ELIMINARMARCA (
  MAR_ID_ INT(10)
)
BEGIN
DELETE FROM concesionarios.GC_MARCA WHERE MAR_ID = MAR_ID_;
END
DELIMITER $$
-- ACTUALIZAR MARCA
DELIMITER $$
CREATE PROCEDURE SP_MODIFICARMARCA (
  MAR_ID_ INT(10),
  MAR_NOMBRE_ VARCHAR(45)
)
BEGIN
UPDATE concesionarios.GC_MARCA SET MAR_ID = MAR_ID_, MAR_NOMBRE = MAR_NOMBRE_ WHERE MAR_ID = MAR_ID_;
END
DELIMITER $$

-- ////////////////////////////////////////////////////////////////////////////////////////////////////
-- MODELO PROCEDURES
-- ////////////////////////////////////////////////////////////////////////////////////////////////////

-- AGREGAR MODELO
DELIMITER $$
CREATE PROCEDURE SP_AGREGARMODELO (
  MOD_ID_ INT(11),
  MOD_NOMBRE_ VARCHAR(80),
  MOD_MARID_ INT(10)
)
BEGIN
INSERT INTO concesionarios.GC_MODELO (MOD_ID, MOD_NOMBRE, MOD_MARID) VALUES (MOD_ID_, MOD_NOMBRE_, MOD_MARID_);
END
DELIMITER $$
-- BORRAR MODELO
DELIMITER $$
CREATE PROCEDURE SP_ELIMINARMODELO (
  MOD_ID_ INT(11)
)
BEGIN
DELETE FROM concesionarios.GC_MODELO WHERE MOD_ID = MOD_ID_;
END
DELIMITER $$
-- ACTUALIZAR MODELO
DELIMITER $$
CREATE PROCEDURE SP_MODIFICARMODELO (
  MOD_ID_ INT(11),
  MOD_NOMBRE_ VARCHAR(80),
  MOD_MARID_ INT(10)
)
BEGIN
UPDATE concesionarios.GC_MODELO SET MOD_ID = MOD_ID_, MOD_NOMBRE = MOD_NOMBRE_, MOD_MARID = MOD_MARID_ WHERE MOD_ID = MOD_ID_;
END
DELIMITER $$

-- ////////////////////////////////////////////////////////////////////////////////////////////////////
-- REPARACIONES PROCEDURES
-- ////////////////////////////////////////////////////////////////////////////////////////////////////

-- AGREGAR REPARACION
DELIMITER $$
CREATE PROCEDURE SP_AGREGARREPARACION (
  REP_ID_ INT(10),
  REP_FECHAINICIO_ DATE,
  REP_FECHAFIN_ DATE,
  REP_CLIENTE_ VARCHAR(80),
  REP_TELEFONO_ INT(15),
  REP_FACID_ INT(10),
  REP_REVISION_ VARCHAR(200),
  REP_VEIHID_ INT(10)
)
BEGIN
INSERT INTO concesionarios.GC_REPARACIONES (REP_ID, REP_FECHAINICIO, REP_FECHAFIN, REP_CLIENTE, REP_TELEFONO, REP_FACID, REP_REVISION, REP_VEIHID) VALUES (REP_ID_, REP_FECHAINICIO_, REP_FECHAFIN_, REP_CLIENTE_, REP_TELEFONO_, REP_FACID_, REP_REVISION_, REP_VEIHID_);
END
DELIMITER $$
-- BORRAR REPARACION
DELIMITER $$
CREATE PROCEDURE SP_ELIMINARREPARACION (
  REP_ID_ INT(10)
)
BEGIN
DELETE FROM concesionarios.GC_REPARACIONES WHERE REP_ID = REP_ID_;
END
DELIMITER $$
-- ACTUALIZAR REPARACION
DELIMITER $$
CREATE PROCEDURE SP_MODIFICARREPARACION (
  REP_ID_ INT(10),
  REP_FECHAINICIO_ DATE,
  REP_FECHAFIN_ DATE,
  REP_CLIENTE_ VARCHAR(80),
  REP_TELEFONO_ INT(15),
  REP_FACID_ INT(10),
  REP_REVISION_ VARCHAR(200),
  REP_VEIHID_ INT(10)
)
BEGIN
UPDATE concesionarios.GC_REPARACIONES SET REP_ID = REP_ID_, REP_FECHAINICIO = REP_FECHAINICIO_, REP_FECHAFIN = REP_FECHAFIN_, REP_CLIENTE = REP_CLIENTE_, REP_TELEFONO = REP_TELEFONO_, REP_FACID = REP_FACID_, REP_REVISION = REP_REVISION_, REP_VEIHID = REP_VEIHID_ WHERE REP_ID = REP_ID_;
END
DELIMITER $$