CREATE SCHEMA IF NOT EXISTS concesionarios DEFAULT CHARACTER SET utf8 ;
USE concesionarios ;

-- -----------------------------------------------------
-- Table concesionarios.GC_CONCESIONARIO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_CONCESIONARIO (
  CON_ID INT(10) NOT NULL,
  CON_NOMBRE VARCHAR(80) NOT NULL,
  CON_DIRECCION VARCHAR(100) NOT NULL,
  CON_TELEFONO INT(15) NOT NULL,
  PRIMARY KEY (CON_ID))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table concesionarios.GC_EMPLEADO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_EMPLEADO (
  EMP_ID VARCHAR(30) NOT NULL,
  EMP_CONID VARCHAR(45) NOT NULL,
  EMP_NOMBRE VARCHAR(80) NOT NULL,
  EMP_APELLIDOS VARCHAR(45) NOT NULL,
  EMP_DIRECCION VARCHAR(100) NOT NULL,
  EMP_TELEFONO VARCHAR(15) NOT NULL,
  EMP_DNI VARCHAR(45) NOT NULL,
  EMP_SUELDO DOUBLE NOT NULL,
  EMP_JEFE VARCHAR(100) NOT NULL,
  EMP_FECHAALTA DATE NOT NULL,
  EMP_FECHABAJA DATE NOT NULL,
  EMP_TIPOEMP VARCHAR(40) NOT NULL,
  GC_CONCESIONARIO_CON_ID INT(10) NOT NULL,
  PRIMARY KEY (EMP_ID),
  INDEX fk_GC_EMPLEADO_GC_CONCESIONARIO1_idx (GC_CONCESIONARIO_CON_ID ASC),
  CONSTRAINT fk_GC_EMPLEADO_GC_CONCESIONARIO1 FOREIGN KEY (GC_CONCESIONARIO_CON_ID) REFERENCES concesionarios.GC_CONCESIONARIO (CON_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table concesionarios.GC_USUARIO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_USUARIO (
  USR_ID VARCHAR(80) NOT NULL,
  USR_PASS VARCHAR(45) NOT NULL,
  USR_PERMISOS VARCHAR(3) NOT NULL,
  GC_EMPLEADO_EMP_ID VARCHAR(30) NOT NULL,
  PRIMARY KEY (USR_ID),
  INDEX fk_GC_USUARIO_GC_EMPLEADO1_idx (GC_EMPLEADO_EMP_ID ASC) ,
  CONSTRAINT fk_GC_USUARIO_GC_EMPLEADO1 FOREIGN KEY (GC_EMPLEADO_EMP_ID) REFERENCES concesionarios.GC_EMPLEADO (EMP_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table concesionarios.GC_CLIENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_CLIENTE (
  CLI_ID INT(10) NOT NULL,
  CLI_NOMBRE VARCHAR(80) NOT NULL,
  CLI_APELLIDOS VARCHAR(80) NOT NULL,
  CLI_TELEFONO INT(15) NOT NULL,
  CLI_EMAIL VARCHAR(45) NULL,
  CLI_FNAC DATE NULL,
  CLI_PROFESION VARCHAR(45) NULL,
  PRIMARY KEY (CLI_ID))
ENGINE = InnoDB;

DELIMITER $$
CREATE PROCEDURE SP_AGREGARCLIENTE (
  CLI_ID_ INT(10),
  CLI_NOMBRE_ VARCHAR(80),
  CLI_APELLIDOS_ VARCHAR(80),
  CLI_TELEFONO_ INT(15),
  CLI_EMAIL_ VARCHAR(45),
  CLI_FNAC_ DATE,
  CLI_PROFESION_ VARCHAR(45)
)
BEGIN
	INSERT INTO concesionario.GC_CLIENTE(CLI_ID,CLI_NOMBRE,CLI_APELLIDOS,CLI_TELEFONO,CLI_EMAIL,CLI_FNAC,CLI_PROFESION)
										 VALUES(CLI_ID_,CLI_NOMBRE_,CLI_APELLIDOS_,CLI_TELEFONO_,CLI_EMAIL_,CLI_FNAC_,CLI_PROFESION_);
END
DELIMITER $$

DELIMITER $$
	CREATE PROCEDURE SP_BORRARCLIENTE(
    CLI_ID_ INT(10)
    )
BEGIN 
	DELETE FROM concesionarios.GC_CLIENTE WHERE CLI_ID = CLI_ID_;
END

DELIMITER $$


-- -----------------------------------------------------
-- Table concesionarios.GC_VENTA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_VENTA (
  VEN_ID INT(10) NOT NULL,
  VEN_VEHID INT(10) NOT NULL,
  VEN_CLIID INT(10) NOT NULL,
  VEN_FECHA DATE NOT NULL,
  VEN_EMPID INT(30) NOT NULL,
  VEN_FACID INT(10) NOT NULL,
  GC_CLIENTE_CLI_ID INT(10) NOT NULL,
  PRIMARY KEY (VEN_ID),
  INDEX fk_GC_VENTA_GC_CLIENTE1_idx (GC_CLIENTE_CLI_ID ASC) ,
  CONSTRAINT fk_GC_VENTA_GC_CLIENTE1 FOREIGN KEY (GC_CLIENTE_CLI_ID) REFERENCES concesionarios.GC_CLIENTE (CLI_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table concesionarios.GC_FACTURA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_FACTURA (
  FAC_ID INT(10) NOT NULL,
  FAC_CONTABILIZADA VARCHAR(45) NOT NULL,
  GC_USUARIO_USR_ID VARCHAR(80) NOT NULL,
  GC_VENTA_VEN_ID INT(10) NOT NULL,
  PRIMARY KEY (FAC_ID),
  INDEX fk_GC_FACTURA_GC_USUARIO1_idx (GC_USUARIO_USR_ID ASC) ,
  INDEX fk_GC_FACTURA_GC_VENTA1_idx (GC_VENTA_VEN_ID ASC) ,
  CONSTRAINT fk_GC_FACTURA_GC_USUARIO1
    FOREIGN KEY (GC_USUARIO_USR_ID) REFERENCES concesionarios.GC_USUARIO (USR_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_GC_FACTURA_GC_VENTA1 FOREIGN KEY (GC_VENTA_VEN_ID) REFERENCES concesionarios.GC_VENTA (VEN_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table concesionarios.GC_MARCA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_MARCA (
  MAR_ID INT(10) NOT NULL,
  MAR_NOMBRE VARCHAR(45) NOT NULL,
  GC_USUARIO_USR_ID VARCHAR(80) NOT NULL,
  PRIMARY KEY (MAR_ID),
  INDEX fk_GC_MARCA_GC_USUARIO1_idx (GC_USUARIO_USR_ID ASC) ,
  CONSTRAINT fk_GC_MARCA_GC_USUARIO1 FOREIGN KEY (GC_USUARIO_USR_ID) REFERENCES concesionarios.GC_USUARIO (USR_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table concesionarios.GC_CATALOGO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_CATALOGO (
  CAT_ID INT(10) NOT NULL,
  CAT_CARID INT(10) NOT NULL,
  CAT_MODID INT(10) NOT NULL,
  CAT_EXTRA VARCHAR(200) NOT NULL,
  CAT_PVP DECIMAL(20,3) NULL,
  GC_CONCESIONARIO_CON_ID INT(10) NOT NULL,
  PRIMARY KEY (CAT_ID),
  INDEX fk_GC_CATALOGO_GC_CONCESIONARIO1_idx (GC_CONCESIONARIO_CON_ID ASC) ,
  CONSTRAINT fk_GC_CATALOGO_GC_CONCESIONARIO1 FOREIGN KEY (GC_CONCESIONARIO_CON_ID) REFERENCES concesionarios.GC_CONCESIONARIO (CON_ID)
    
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table concesionarios.GC_MODELO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_MODELO (
  MOD_ID INT NOT NULL,
  MOD_NOMBRE VARCHAR(80) NOT NULL,
  MOD_MARID INT(10) NOT NULL,
  GC_MARCA_MAR_ID INT(10) NOT NULL,
  GC_CATALOGO_CAT_ID INT(10) NOT NULL,
  PRIMARY KEY (MOD_ID),
  INDEX fk_GC_MODELO_GC_MARCA1_idx (GC_MARCA_MAR_ID ASC) ,
  INDEX fk_GC_MODELO_GC_CATALOGO1_idx (GC_CATALOGO_CAT_ID ASC) ,
  CONSTRAINT fk_GC_MODELO_GC_MARCA1 FOREIGN KEY (GC_MARCA_MAR_ID) REFERENCES concesionarios.GC_MARCA (MAR_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_GC_MODELO_GC_CATALOGO1 FOREIGN KEY (GC_CATALOGO_CAT_ID) REFERENCES concesionarios.GC_CATALOGO (CAT_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table concesionarios.GC_VEHICULO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_VEHICULO (
  VEH_ID INT(10) NOT NULL,
  VEH_BASTIDOR VARCHAR(80) NOT NULL,
  VEH_MATRICULA VARCHAR(15) NOT NULL,
  VEH_COLOR VARCHAR(45) NOT NULL,
  VEH_MODID INT(10) NOT NULL,
  VEH_VENDIDO VARCHAR(30) NOT NULL,
  GC_MODELO_MOD_ID INT NOT NULL,
  GC_VENTA_VEN_ID INT(10) NOT NULL,
  PRIMARY KEY (VEH_ID),
  INDEX fk_GC_VEHICULO_GC_MODELgc_vehiculoO1_idx (GC_MODELO_MOD_ID ASC) ,
  INDEX fk_GC_VEHICULO_GC_VENTA1_idx (GC_VENTA_VEN_ID ASC) ,
  CONSTRAINT fk_GC_VEHICULO_GC_MODELO1 FOREIGN KEY (GC_MODELO_MOD_ID) REFERENCES concesionarios.GC_MODELO (MOD_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_GC_VEHICULO_GC_VENTA1 FOREIGN KEY (GC_VENTA_VEN_ID) REFERENCES concesionarios.GC_VENTA (VEN_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- ALTER TABLE concesionarios.GC_VEHICULO DROP COLUMN VEH_MODID;

-- -----------------------------------------------------
-- Table concesionarios.GC_REPARACIONES
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_REPARACIONES (
  REP_ID INT(10) NOT NULL,
  REP_FECHAINICIO DATE NOT NULL,
  REP_FECHAFIN DATE NULL,
  REP_CLIENTE VARCHAR(80) NOT NULL,
  REP_TELEFONO INT(15) NOT NULL,
  REP_FACID INT(10) NOT NULL,
  REP_REVISION VARCHAR(200) NOT NULL,
  REP_VEIHID INT(10) NULL,
  GC_VEHICULO_VEH_ID INT(10) NOT NULL,
  GC_EMPLEADO_EMP_ID VARCHAR(30) NOT NULL,
  PRIMARY KEY (REP_ID),
  INDEX fk_GC_REPARACIONES_GC_VEHICULO1_idx (GC_VEHICULO_VEH_ID ASC) ,
  INDEX fk_GC_REPARACIONES_GC_EMPLEADO1_idx (GC_EMPLEADO_EMP_ID ASC) ,
  CONSTRAINT fk_GC_REPARACIONES_GC_VEHICULO1 FOREIGN KEY (GC_VEHICULO_VEH_ID) REFERENCES concesionarios.GC_VEHICULO (VEH_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_GC_REPARACIONES_GC_EMPLEADO1 FOREIGN KEY (GC_EMPLEADO_EMP_ID) REFERENCES concesionarios.GC_EMPLEADO (EMP_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table concesionarios.GC_TAREA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_TAREA (
  TAR_ID INT(10) NOT NULL,
  TAR_REPID INT(10) NOT NULL,
  TAR_CONCEPTO VARCHAR(200) NOT NULL,
  TAR_HORAS INT(10) NOT NULL,
  TAR_EMPID VARCHAR(30) NOT NULL,
  TAR_FACTURABLE VARCHAR(45) NOT NULL,
  GC_EMPLEADO_EMP_ID VARCHAR(30) NOT NULL,
  PRIMARY KEY (TAR_ID),
  INDEX fk_GC_TAREA_GC_EMPLEADO1_idx (GC_EMPLEADO_EMP_ID ASC) ,
  CONSTRAINT fk_GC_TAREA_GC_EMPLEADO1 FOREIGN KEY (GC_EMPLEADO_EMP_ID) REFERENCES concesionarios.GC_EMPLEADO (EMP_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE concesionarios.GC_TAREA add column TAR_ESTADO BOOLEAN;

-- -----------------------------------------------------
-- Table concesionarios.GC_LINEAFACTURA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_LINEAFACTURA (
  LIN_ID INT(10) NOT NULL,
  LIN_FACID INT(10) NOT NULL,
  LIN_CONCEPTO VARCHAR(200) NOT NULL,
  LIN_COSTE INT(10) NOT NULL,
  GC_VENTA_VEN_ID INT(10) NOT NULL,
  PRIMARY KEY (LIN_ID),
  INDEX fk_GC_LINEAFACTURA_GC_VENTA1_idx (GC_VENTA_VEN_ID ASC) ,
  CONSTRAINT fk_GC_LINEAFACTURA_GC_VENTA1 FOREIGN KEY (GC_VENTA_VEN_ID) REFERENCES concesionarios.GC_VENTA (VEN_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table concesionarios.GC_CONFIGURACION
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_CONFIGURACION (
  CONF_VEHID INT(10) NOT NULL,
  CONF_CARID INT(10) NOT NULL,
  GC_VEHICULO_VEH_ID INT(10) NOT NULL,
  CONF_MOTOR VARCHAR(35) NOT NULL,
  CONF_LLANTAS VARCHAR(20) NOT NULL,
  CONF_ESPEJOS VARCHAR(20) NOT NULL,
  CONF_CHASIS VARCHAR(35) NULL,
  CONF_CILINDRAJE VARCHAR(50) NULL,
  CONF_RINES VARCHAR(30) NULL,
  CONF_INTERIOR VARCHAR(10) NULL,
  PRIMARY KEY (CONF_VEHID),
  INDEX fk_GC_CONFIGURACION_GC_VEHICULO1_idx (GC_VEHICULO_VEH_ID ASC) ,
  CONSTRAINT fk_GC_CONFIGURACION_GC_VEHICULO1 FOREIGN KEY (GC_VEHICULO_VEH_ID) REFERENCES concesionarios.GC_VEHICULO (VEH_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table concesionarios.GC_CARACTERISTICA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_CARACTERISTICA (
  CAR_ID INT(10) NOT NULL,
  CAR_DESCRIPCION VARCHAR(100) NOT NULL,
  CAR_MAXVEL VARCHAR(45) NOT NULL,
  CAR_MAXTORQUE VARCHAR(45) NOT NULL,
  CAR_TIPOCOMBUSTIBLE VARCHAR(35) NOT NULL,
  CAR_ACELERACION VARCHAR(45) NOT NULL,
  CAR_KILOMETRAJE VARCHAR(25) NOT NULL,
  CAR_SUSPENSION VARCHAR(100) NOT NULL,
  CAR_RADIADOR VARCHAR(500) NULL,
  PRIMARY KEY (CAR_ID))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table concesionarios.GC_MODELO_has_GC_CARACTERISTICA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_MODELO_has_GC_CARACTERISTICA (
  GC_MODELO_MOD_ID INT NOT NULL,
  GC_CARACTERISTICA_CAR_ID INT(10) NOT NULL,
  PRIMARY KEY (GC_MODELO_MOD_ID, GC_CARACTERISTICA_CAR_ID),
  INDEX fk_GC_MODELO_has_GC_CARACTERISTICA_GC_CARACTERISTICA1_idx (GC_CARACTERISTICA_CAR_ID ASC) ,
  INDEX fk_GC_MODELO_has_GC_CARACTERISTICA_GC_MODELO1_idx (GC_MODELO_MOD_ID ASC) ,
  CONSTRAINT fk_GC_MODELO_has_GC_CARACTERISTICA_GC_MODELO1 FOREIGN KEY (GC_MODELO_MOD_ID) REFERENCES concesionarios.GC_MODELO (MOD_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_GC_MODELO_has_GC_CARACTERISTICA_GC_CARACTERISTICA1 FOREIGN KEY (GC_CARACTERISTICA_CAR_ID) REFERENCES concesionarios.GC_CARACTERISTICA (CAR_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table concesionarios.GC_VEHICULO_has_GC_MODELO_has_GC_CARACTERISTICA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_VEHICULO_has_GC_MODELO_has_GC_CARACTERISTICA (
  GC_VEHICULO_VEH_ID INT(10) NOT NULL,
  GC_MODELO_has_GC_CARACTERISTICA_GC_MODELO_MOD_ID INT NOT NULL,
  GC_MODELO_has_GC_CARACTERISTICA_GC_CARACTERISTICA_CAR_ID INT(10) NOT NULL,
  PRIMARY KEY (GC_VEHICULO_VEH_ID, GC_MODELO_has_GC_CARACTERISTICA_GC_MODELO_MOD_ID, GC_MODELO_has_GC_CARACTERISTICA_GC_CARACTERISTICA_CAR_ID),
  INDEX fk_GC_VEHICULO_has_GC_MODELO_has_GC_CARACTERISTICA_GC_MODEL_idx (GC_MODELO_has_GC_CARACTERISTICA_GC_MODELO_MOD_ID ASC, GC_MODELO_has_GC_CARACTERISTICA_GC_CARACTERISTICA_CAR_ID ASC) ,
  INDEX fk_GC_VEHICULO_has_GC_MODELO_has_GC_CARACTERISTICA_GC_VEHIC_idx (GC_VEHICULO_VEH_ID ASC) ,
  CONSTRAINT fk_GC_VEHICULO_has_GC_MODELO_has_GC_CARACTERISTICA_GC_VEHICULO1 FOREIGN KEY (GC_VEHICULO_VEH_ID)
    REFERENCES concesionarios.GC_VEHICULO (VEH_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_GC_VEHICULO_has_GC_MODELO_has_GC_CARACTERISTICA_GC_MODELO_1 
	FOREIGN KEY (GC_MODELO_has_GC_CARACTERISTICA_GC_MODELO_MOD_ID , GC_MODELO_has_GC_CARACTERISTICA_GC_CARACTERISTICA_CAR_ID)
    REFERENCES concesionarios.GC_MODELO_has_GC_CARACTERISTICA (GC_MODELO_MOD_ID , GC_CARACTERISTICA_CAR_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table concesionarios.GC_VEHICULO_has_GC_CARACTERISTICA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_VEHICULO_has_GC_CARACTERISTICA (
  GC_VEHICULO_VEH_ID INT(10) NOT NULL,
  GC_CARACTERISTICA_CAR_ID INT(10) NOT NULL,
  PRIMARY KEY (GC_VEHICULO_VEH_ID, GC_CARACTERISTICA_CAR_ID),
  INDEX fk_GC_VEHICULO_has_GC_CARACTERISTICA_GC_CARACTERISTICA1_idx (GC_CARACTERISTICA_CAR_ID ASC) ,
  INDEX fk_GC_VEHICULO_has_GC_CARACTERISTICA_GC_VEHICULO1_idx (GC_VEHICULO_VEH_ID ASC) ,
  CONSTRAINT fk_GC_VEHICULO_has_GC_CARACTERISTICA_GC_VEHICULO1 FOREIGN KEY (GC_VEHICULO_VEH_ID) REFERENCES concesionarios.GC_VEHICULO (VEH_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_GC_VEHICULO_has_GC_CARACTERISTICA_GC_CARACTERISTICA1 FOREIGN KEY (GC_CARACTERISTICA_CAR_ID) REFERENCES concesionarios.GC_CARACTERISTICA (CAR_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table concesionarios.GC_MODELO_has_GC_CARACTERISTICA1
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS concesionarios.GC_MODELO_has_GC_CARACTERISTICA1 (
  GC_MODELO_MOD_ID INT NOT NULL,
  GC_CARACTERISTICA_CAR_ID INT(10) NOT NULL,
  PRIMARY KEY (GC_MODELO_MOD_ID, GC_CARACTERISTICA_CAR_ID),
  INDEX fk_GC_MODELO_has_GC_CARACTERISTICA1_GC_CARACTERISTICA1_idx (GC_CARACTERISTICA_CAR_ID ASC) ,
  INDEX fk_GC_MODELO_has_GC_CARACTERISTICA1_GC_MODELO1_idx (GC_MODELO_MOD_ID ASC) ,
  CONSTRAINT fk_GC_MODELO_has_GC_CARACTERISTICA1_GC_MODELO1 FOREIGN KEY (GC_MODELO_MOD_ID) REFERENCES concesionarios.GC_MODELO (MOD_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_GC_MODELO_has_GC_CARACTERISTICA1_GC_CARACTERISTICA1 FOREIGN KEY (GC_CARACTERISTICA_CAR_ID) REFERENCES concesionarios.GC_CARACTERISTICA (CAR_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE concesionarios.GC_DESCUENTOS(
	DES_ID INT(10),
	DES_VALOR double,
	DES_NOMBRE VARCHAR(100),
    DES_FACTURAID INT(10),
    FAC_ID INT(10),
    PRIMARY KEY(DES_ID),
    CONSTRAINT FK_GC_DESCUENTOS FOREIGN KEY (DES_FACTURAID) references concesionarios.gc_factura(FAC_ID)
);
